# Generated by Django 4.2.10 on 2025-04-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Risco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "probabilidade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "impacto",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Médio"),
                            ("ALTO", "Alto"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDENTIFICADO", "Identificado"),
                            ("EM_ANALISE", "Em Análise"),
                            ("MITIGADO", "Mitigado"),
                            ("ACEITO", "Aceito"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        default="IDENTIFICADO",
                        max_length=20,
                    ),
                ),
                ("plano_mitigacao", models.TextField(blank=True, null=True)),
                ("plano_contingencia", models.TextField(blank=True, null=True)),
                ("data_identificacao", models.DateField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="riscos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riscos",
                        to="projects.projeto",
                    ),
                ),
                (
                    "responsavel_mitigacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="riscos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risco",
                "verbose_name_plural": "Riscos",
                "ordering": ["-data_identificacao"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoRisco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_anterior",
                    models.CharField(
                        choices=[
                            ("IDENTIFICADO", "Identificado"),
                            ("EM_ANALISE", "Em Análise"),
                            ("MITIGADO", "Mitigado"),
                            ("ACEITO", "Aceito"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "novo_status",
                    models.CharField(
                        choices=[
                            ("IDENTIFICADO", "Identificado"),
                            ("EM_ANALISE", "Em Análise"),
                            ("MITIGADO", "Mitigado"),
                            ("ACEITO", "Aceito"),
                            ("ELIMINADO", "Eliminado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "probabilidade_anterior",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "nova_probabilidade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "impacto_anterior",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Médio"),
                            ("ALTO", "Alto"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "novo_impacto",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Médio"),
                            ("ALTO", "Alto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="risks.risco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Risco",
                "verbose_name_plural": "Históricos de Riscos",
                "ordering": ["-alterado_em"],
            },
        ),
    ]
