# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('projects', '0003_historicostatusprojeto_tenant_membroprojeto_tenant_and_more'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicorisco',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risco',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='historicorisco',
            index=models.Index(fields=['tenant', '-alterado_em'], name='risks_histo_tenant__f23d69_idx'),
        ),
        migrations.AddIndex(
            model_name='risco',
            index=models.Index(fields=['tenant', '-data_identificacao'], name='risks_risco_tenant__34660a_idx'),
        ),
    ]
