# Generated by Django 4.2.10 on 2025-04-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "anexo",
                    models.FileField(blank=True, null=True, upload_to="chat_anexos/"),
                ),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("editado", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="projects.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Chat",
                "verbose_name_plural": "Mensagens de Chat",
                "ordering": ["enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TAREFA", "Tarefa"),
                            ("PROJETO", "Projeto"),
                            ("EQUIPE", "Equipe"),
                            ("RISCO", "Risco"),
                            ("DOCUMENTO", "Documento"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("lida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="URL para redirecionamento",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.projeto",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.tarefa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoNotificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tarefa_atribuida",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="AMBOS",
                        max_length=10,
                    ),
                ),
                (
                    "tarefa_comentario",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "tarefa_prazo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="AMBOS",
                        max_length=10,
                    ),
                ),
                (
                    "projeto_status",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "equipe_alteracao",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "documento_novo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "risco_novo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "mensagem_chat",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SISTEMA", "Sistema"),
                            ("AMBOS", "Ambos"),
                            ("NENHUM", "Nenhum"),
                        ],
                        default="SISTEMA",
                        max_length=10,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificação",
                "verbose_name_plural": "Configurações de Notificações",
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="projects.projeto",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="received_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicação",
                "verbose_name_plural": "Comunicações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMensagemLeitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "mensagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="communications.chatmensagem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_lidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura de Mensagem",
                "verbose_name_plural": "Leituras de Mensagens",
                "unique_together": {("mensagem", "usuario")},
            },
        ),
    ]
