# Generated by Django 5.2.1 on 2025-06-05 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_comunicacao_delete_communication'),
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
        ('tasks', '0002_tarefa_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacao',
            name='tipo',
            field=models.CharField(choices=[('ATA', 'Ata de Reunião'), ('MEMORANDO', 'Memorando'), ('RELATORIO', 'Relatório'), ('OFICIO', 'Ofício'), ('COMUNICADO', 'Comunicado Geral'), ('OUTRO', 'Outro')], default='OUTRO', help_text='Tipo de comunicação formal', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='anexo',
            field=models.FileField(blank=True, help_text='Arquivo opcional anexado à mensagem', null=True, upload_to='chat_anexos/'),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='autor',
            field=models.ForeignKey(help_text='Usuário que enviou a mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='editado',
            field=models.BooleanField(default=False, help_text='Indica se a mensagem foi editada após o envio inicial'),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='enviado_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi enviada'),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto ao qual a mensagem pertence', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='projects.projeto'),
        ),
        migrations.AlterField(
            model_name='chatmensagem',
            name='texto',
            field=models.TextField(help_text='Conteúdo da mensagem'),
        ),
        migrations.AlterField(
            model_name='chatmensagemleitura',
            name='lido_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a mensagem foi lida'),
        ),
        migrations.AlterField(
            model_name='chatmensagemleitura',
            name='mensagem',
            field=models.ForeignKey(help_text='Mensagem que foi lida', on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='communications.chatmensagem'),
        ),
        migrations.AlterField(
            model_name='chatmensagemleitura',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que leu a mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_lidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da comunicação'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a comunicação foi criada'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='destinatarios',
            field=models.ManyToManyField(help_text='Usuários que receberam esta comunicação', related_name='comunicacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='projeto',
            field=models.ForeignKey(help_text='Projeto ao qual esta comunicação está associada', on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='projects.projeto'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='remetente',
            field=models.ForeignKey(help_text='Usuário que enviou a comunicação', on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='texto',
            field=models.TextField(help_text='Conteúdo detalhado da comunicação'),
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='titulo',
            field=models.CharField(help_text='Título ou assunto da comunicação', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='documento_novo',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação quando um novo documento é adicionado', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='equipe_alteracao',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação quando há alterações na equipe de um projeto', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='mensagem_chat',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação para novas mensagens de chat', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='projeto_status',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação quando o status de um projeto é alterado', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='risco_novo',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação quando um novo risco é registrado', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='tarefa_atribuida',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='AMBOS', help_text='Canal de notificação quando uma tarefa é atribuída ao usuário', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='tarefa_comentario',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='SISTEMA', help_text='Canal de notificação quando há um novo comentário em uma tarefa do usuário', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='tarefa_prazo',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('SISTEMA', 'Sistema'), ('AMBOS', 'Ambos'), ('NENHUM', 'Nenhum')], default='AMBOS', help_text='Canal de notificação para lembretes de prazo de tarefas', max_length=10),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='usuario',
            field=models.OneToOneField(help_text='Usuário ao qual estas configurações pertencem', on_delete=django.db.models.deletion.CASCADE, related_name='config_notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a notificação foi criada'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida',
            field=models.BooleanField(default=False, help_text='Indica se a notificação foi lida pelo usuário'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='lida_em',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a notificação foi lida (se aplicável)', null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='mensagem',
            field=models.TextField(help_text='Conteúdo detalhado da notificação'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', help_text='Nível de prioridade da notificação', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto relacionado à notificação (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projeto'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tarefa',
            field=models.ForeignKey(blank=True, help_text='Tarefa relacionada à notificação (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tarefa'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('TAREFA', 'Tarefa'), ('PROJETO', 'Projeto'), ('EQUIPE', 'Equipe'), ('RISCO', 'Risco'), ('DOCUMENTO', 'Documento'), ('SISTEMA', 'Sistema')], help_text='Tipo de objeto relacionado à notificação', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(help_text='Título breve da notificação', max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, help_text='URL para redirecionamento quando a notificação for clicada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que receberá a notificação', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
