# Generated by Django 5.2.1 on 2025-06-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_comunicacao_tipo_alter_chatmensagem_anexo_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0003_add_generic_foreign_key'),
        ('tasks', '0002_tarefa_atualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='O tipo do objeto relacionado (ex: Projeto, Tarefa, Risco).', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='O ID do objeto relacionado.', null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto relacionado à notificação (se aplicável) - DEPRECATED', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projeto'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tarefa',
            field=models.ForeignKey(blank=True, help_text='Tarefa relacionada à notificação (se aplicável) - DEPRECATED', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tarefa'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('TAREFA', 'Tarefa'), ('PROJETO', 'Projeto'), ('EQUIPE', 'Equipe'), ('RISCO', 'Risco'), ('DOCUMENTO', 'Documento'), ('SISTEMA', 'Sistema'), ('CHAT', 'Chat')], help_text='Tipo de objeto relacionado à notificação', max_length=20),
        ),
    ]
