# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_comunicacao_tipo_alter_chatmensagem_anexo_and_more'),
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
        ('tasks', '0002_tarefa_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmensagem',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmensagemleitura',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacao',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='chatmensagem',
            index=models.Index(fields=['tenant', 'enviado_em'], name='communicati_tenant__12530d_idx'),
        ),
        migrations.AddIndex(
            model_name='comunicacao',
            index=models.Index(fields=['tenant', '-criada_em'], name='communicati_tenant__3a5c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tenant', '-criada_em'], name='communicati_tenant__5b42c7_idx'),
        ),
    ]
