/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  PaginatedPermissaoEquipeList,
  PatchedPermissaoEquipeRequest,
  PermissaoEquipe,
  PermissaoEquipeRequest,
  TeamsPermissoesListParams,
} from ".././schemas";

import { customMutator } from "../../lib/axios-instance";
import type { ErrorType } from "../../lib/axios-instance";

/**
 * Retorna uma lista de permissões de equipe.
 * @summary Listar permissões de equipe
 */
export const teamsPermissoesList = (
  params?: MaybeRef<TeamsPermissoesListParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customMutator<PaginatedPermissaoEquipeList>({
    url: `/api/teams/permissoes/`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getTeamsPermissoesListQueryKey = (
  params?: MaybeRef<TeamsPermissoesListParams>,
) => {
  return ["api", "teams", "permissoes", ...(params ? [params] : [])] as const;
};

export const getTeamsPermissoesListQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsPermissoesList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<TeamsPermissoesListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof teamsPermissoesList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getTeamsPermissoesListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof teamsPermissoesList>>
  > = ({ signal }) => teamsPermissoesList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsPermissoesList>>,
    TError,
    TData
  >;
};

export type TeamsPermissoesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesList>>
>;
export type TeamsPermissoesListQueryError = ErrorType<unknown>;

/**
 * @summary Listar permissões de equipe
 */

export function useTeamsPermissoesList<
  TData = Awaited<ReturnType<typeof teamsPermissoesList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<TeamsPermissoesListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof teamsPermissoesList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTeamsPermissoesListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Cria uma nova permissão de equipe.
 * @summary Criar permissão
 */
export const teamsPermissoesCreate = (
  permissaoEquipeRequest: MaybeRef<PermissaoEquipeRequest>,
  signal?: AbortSignal,
) => {
  permissaoEquipeRequest = unref(permissaoEquipeRequest);

  return customMutator<PermissaoEquipe>({
    url: `/api/teams/permissoes/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: permissaoEquipeRequest,
    signal,
  });
};

export const getTeamsPermissoesCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsPermissoesCreate>>,
    TError,
    { data: PermissaoEquipeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsPermissoesCreate>>,
  TError,
  { data: PermissaoEquipeRequest },
  TContext
> => {
  const mutationKey = ["teamsPermissoesCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsPermissoesCreate>>,
    { data: PermissaoEquipeRequest }
  > = (props) => {
    const { data } = props ?? {};

    return teamsPermissoesCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsPermissoesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesCreate>>
>;
export type TeamsPermissoesCreateMutationBody = PermissaoEquipeRequest;
export type TeamsPermissoesCreateMutationError = ErrorType<unknown>;

/**
 * @summary Criar permissão
 */
export const useTeamsPermissoesCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsPermissoesCreate>>,
      TError,
      { data: PermissaoEquipeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof teamsPermissoesCreate>>,
  TError,
  { data: PermissaoEquipeRequest },
  TContext
> => {
  const mutationOptions = getTeamsPermissoesCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retorna detalhes de uma permissão específica.
 * @summary Obter detalhes da permissão
 */
export const teamsPermissoesRetrieve = (
  id: MaybeRef<number>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customMutator<PermissaoEquipe>({
    url: `/api/teams/permissoes/${id}/`,
    method: "GET",
    signal,
  });
};

export const getTeamsPermissoesRetrieveQueryKey = (id: MaybeRef<number>) => {
  return ["api", "teams", "permissoes", id] as const;
};

export const getTeamsPermissoesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsPermissoesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof teamsPermissoesRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getTeamsPermissoesRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof teamsPermissoesRetrieve>>
  > = ({ signal }) => teamsPermissoesRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsPermissoesRetrieve>>,
    TError,
    TData
  >;
};

export type TeamsPermissoesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesRetrieve>>
>;
export type TeamsPermissoesRetrieveQueryError = ErrorType<unknown>;

/**
 * @summary Obter detalhes da permissão
 */

export function useTeamsPermissoesRetrieve<
  TData = Awaited<ReturnType<typeof teamsPermissoesRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof teamsPermissoesRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTeamsPermissoesRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Atualiza uma permissão de equipe existente.
 * @summary Atualizar permissão
 */
export const teamsPermissoesUpdate = (
  id: MaybeRef<number>,
  permissaoEquipeRequest: MaybeRef<PermissaoEquipeRequest>,
) => {
  id = unref(id);
  permissaoEquipeRequest = unref(permissaoEquipeRequest);

  return customMutator<PermissaoEquipe>({
    url: `/api/teams/permissoes/${id}/`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: permissaoEquipeRequest,
  });
};

export const getTeamsPermissoesUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsPermissoesUpdate>>,
    TError,
    { id: number; data: PermissaoEquipeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsPermissoesUpdate>>,
  TError,
  { id: number; data: PermissaoEquipeRequest },
  TContext
> => {
  const mutationKey = ["teamsPermissoesUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsPermissoesUpdate>>,
    { id: number; data: PermissaoEquipeRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return teamsPermissoesUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsPermissoesUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesUpdate>>
>;
export type TeamsPermissoesUpdateMutationBody = PermissaoEquipeRequest;
export type TeamsPermissoesUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar permissão
 */
export const useTeamsPermissoesUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsPermissoesUpdate>>,
      TError,
      { id: number; data: PermissaoEquipeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof teamsPermissoesUpdate>>,
  TError,
  { id: number; data: PermissaoEquipeRequest },
  TContext
> => {
  const mutationOptions = getTeamsPermissoesUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Atualiza parcialmente uma permissão de equipe.
 * @summary Atualizar permissão parcialmente
 */
export const teamsPermissoesPartialUpdate = (
  id: MaybeRef<number>,
  patchedPermissaoEquipeRequest: MaybeRef<PatchedPermissaoEquipeRequest>,
) => {
  id = unref(id);
  patchedPermissaoEquipeRequest = unref(patchedPermissaoEquipeRequest);

  return customMutator<PermissaoEquipe>({
    url: `/api/teams/permissoes/${id}/`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedPermissaoEquipeRequest,
  });
};

export const getTeamsPermissoesPartialUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>,
    TError,
    { id: number; data: PatchedPermissaoEquipeRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>,
  TError,
  { id: number; data: PatchedPermissaoEquipeRequest },
  TContext
> => {
  const mutationKey = ["teamsPermissoesPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>,
    { id: number; data: PatchedPermissaoEquipeRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return teamsPermissoesPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsPermissoesPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>
>;
export type TeamsPermissoesPartialUpdateMutationBody =
  PatchedPermissaoEquipeRequest;
export type TeamsPermissoesPartialUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar permissão parcialmente
 */
export const useTeamsPermissoesPartialUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>,
      TError,
      { id: number; data: PatchedPermissaoEquipeRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof teamsPermissoesPartialUpdate>>,
  TError,
  { id: number; data: PatchedPermissaoEquipeRequest },
  TContext
> => {
  const mutationOptions =
    getTeamsPermissoesPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Remove uma permissão de equipe.
 * @summary Excluir permissão
 */
export const teamsPermissoesDestroy = (id: MaybeRef<number>) => {
  id = unref(id);

  return customMutator<void>({
    url: `/api/teams/permissoes/${id}/`,
    method: "DELETE",
  });
};

export const getTeamsPermissoesDestroyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsPermissoesDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsPermissoesDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["teamsPermissoesDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsPermissoesDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return teamsPermissoesDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsPermissoesDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsPermissoesDestroy>>
>;

export type TeamsPermissoesDestroyMutationError = ErrorType<unknown>;

/**
 * @summary Excluir permissão
 */
export const useTeamsPermissoesDestroy = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsPermissoesDestroy>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof teamsPermissoesDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getTeamsPermissoesDestroyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
