# Generated by Django 4.2.7 on 2025-06-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_custo_projeto_alter_custo_tarefa'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membroprojeto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicostatusprojeto',
            name='novo_status',
        ),
        migrations.AddField(
            model_name='projeto',
            name='custos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projeto_custos', to='costs.custo'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.projeto'),
        ),
        migrations.AddConstraint(
            model_name='membroprojeto',
            constraint=models.UniqueConstraint(fields=('projeto', 'usuario'), name='unique_projeto_usuario'),
        ),
        migrations.RemoveField(
            model_name='membroprojeto',
            name='data_entrada',
        ),
    ]
