# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_alerta_tenant_categoria_tenant_custo_tenant_and_more'),
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicostatusprojeto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membroprojeto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='historicostatusprojeto',
            index=models.Index(fields=['tenant', '-alterado_em'], name='projects_hi_tenant__98018c_idx'),
        ),
        migrations.AddIndex(
            model_name='projeto',
            index=models.Index(fields=['tenant', '-criado_em'], name='projects_pr_tenant__2506b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['tenant', 'data_inicio'], name='projects_sp_tenant__d1fc6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(fields=('tenant', 'titulo'), name='uniq_projeto_titulo_por_tenant'),
        ),
    ]
