# Generated by Django 5.2.1 on 2025-06-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='custos',
        ),
    ]
