/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  computed,
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  AtribuicaoTarefa,
  AtribuicaoTarefaRequest,
  PaginatedAtribuicaoTarefaList,
  TasksAtribuicoesListParams,
  TasksTarefasAtribuirResponsavelCreate400,
  TasksTarefasAtribuirResponsavelCreate404,
  TasksTarefasAtribuirResponsavelCreateBody,
  TasksTarefasRemoverResponsavelCreate400,
  TasksTarefasRemoverResponsavelCreate404,
  TasksTarefasRemoverResponsavelCreateBody
} from '.././schemas';





/**
 * Retorna uma lista de atribuições de tarefas a usuários.
 * @summary Listar atribuições de tarefas
 */
export const tasksAtribuicoesList = (
    params?: MaybeRef<TasksAtribuicoesListParams>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAtribuicaoTarefaList>> => {
    params = unref(params);
    
    return axios.get(
      `/api/tasks/atribuicoes/`,{
    ...options,
        params: {...unref(params), ...options?.params},}
    );
  }


export const getTasksAtribuicoesListQueryKey = (params?: MaybeRef<TasksAtribuicoesListParams>,) => {
    return ['api','tasks','atribuicoes', ...(params ? [params]: [])] as const;
    }

    
export const getTasksAtribuicoesListQueryOptions = <TData = Awaited<ReturnType<typeof tasksAtribuicoesList>>, TError = AxiosError<unknown>>(params?: MaybeRef<TasksAtribuicoesListParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getTasksAtribuicoesListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tasksAtribuicoesList>>> = ({ signal }) => tasksAtribuicoesList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesList>>, TError, TData> 
}

export type TasksAtribuicoesListQueryResult = NonNullable<Awaited<ReturnType<typeof tasksAtribuicoesList>>>
export type TasksAtribuicoesListQueryError = AxiosError<unknown>


/**
 * @summary Listar atribuições de tarefas
 */

export function useTasksAtribuicoesList<TData = Awaited<ReturnType<typeof tasksAtribuicoesList>>, TError = AxiosError<unknown>>(
 params?: MaybeRef<TasksAtribuicoesListParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTasksAtribuicoesListQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Atribui uma tarefa a um usuário.
 * @summary Criar atribuição de tarefa
 */
export const tasksAtribuicoesCreate = (
    atribuicaoTarefaRequest: MaybeRef<AtribuicaoTarefaRequest>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AtribuicaoTarefa>> => {
    atribuicaoTarefaRequest = unref(atribuicaoTarefaRequest);
    
    return axios.post(
      `/api/tasks/atribuicoes/`,
      atribuicaoTarefaRequest,options
    );
  }



export const getTasksAtribuicoesCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesCreate>>, TError,{data: AtribuicaoTarefaRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesCreate>>, TError,{data: AtribuicaoTarefaRequest}, TContext> => {

const mutationKey = ['tasksAtribuicoesCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tasksAtribuicoesCreate>>, {data: AtribuicaoTarefaRequest}> = (props) => {
          const {data} = props ?? {};

          return  tasksAtribuicoesCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TasksAtribuicoesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tasksAtribuicoesCreate>>>
    export type TasksAtribuicoesCreateMutationBody = AtribuicaoTarefaRequest
    export type TasksAtribuicoesCreateMutationError = AxiosError<unknown>

    /**
 * @summary Criar atribuição de tarefa
 */
export const useTasksAtribuicoesCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesCreate>>, TError,{data: AtribuicaoTarefaRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof tasksAtribuicoesCreate>>,
        TError,
        {data: AtribuicaoTarefaRequest},
        TContext
      > => {

      const mutationOptions = getTasksAtribuicoesCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retorna informações detalhadas de uma atribuição específica.
 * @summary Obter detalhes de atribuição
 */
export const tasksAtribuicoesRetrieve = (
    id: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AtribuicaoTarefa>> => {
    id = unref(id);
    
    return axios.get(
      `/api/tasks/atribuicoes/${id}/`,options
    );
  }


export const getTasksAtribuicoesRetrieveQueryKey = (id: MaybeRef<number>,) => {
    return ['api','tasks','atribuicoes',id] as const;
    }

    
export const getTasksAtribuicoesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>, TError = AxiosError<unknown>>(id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getTasksAtribuicoesRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>> = ({ signal }) => tasksAtribuicoesRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: computed(() => !!(unref(id))), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>, TError, TData> 
}

export type TasksAtribuicoesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>>
export type TasksAtribuicoesRetrieveQueryError = AxiosError<unknown>


/**
 * @summary Obter detalhes de atribuição
 */

export function useTasksAtribuicoesRetrieve<TData = Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>, TError = AxiosError<unknown>>(
 id: MaybeRef<number>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tasksAtribuicoesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTasksAtribuicoesRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Remove a atribuição de uma tarefa a um usuário.
 * @summary Remover atribuição
 */
export const tasksAtribuicoesDestroy = (
    id: MaybeRef<number>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    id = unref(id);
    
    return axios.delete(
      `/api/tasks/atribuicoes/${id}/`,options
    );
  }



export const getTasksAtribuicoesDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>, TError,{id: number}, TContext> => {

const mutationKey = ['tasksAtribuicoesDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  tasksAtribuicoesDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TasksAtribuicoesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>>
    
    export type TasksAtribuicoesDestroyMutationError = AxiosError<unknown>

    /**
 * @summary Remover atribuição
 */
export const useTasksAtribuicoesDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof tasksAtribuicoesDestroy>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getTasksAtribuicoesDestroyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Atribui um usuário como responsável pela tarefa.
 * @summary Atribuir responsável à tarefa
 */
export const tasksTarefasAtribuirResponsavelCreate = (
    id: MaybeRef<number>,
    tasksTarefasAtribuirResponsavelCreateBody: MaybeRef<TasksTarefasAtribuirResponsavelCreateBody>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AtribuicaoTarefa>> => {
    id = unref(id);
tasksTarefasAtribuirResponsavelCreateBody = unref(tasksTarefasAtribuirResponsavelCreateBody);
    
    return axios.post(
      `/api/tasks/tarefas/${id}/atribuir_responsavel/`,
      tasksTarefasAtribuirResponsavelCreateBody,options
    );
  }



export const getTasksTarefasAtribuirResponsavelCreateMutationOptions = <TError = AxiosError<TasksTarefasAtribuirResponsavelCreate400 | TasksTarefasAtribuirResponsavelCreate404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>, TError,{id: number;data: TasksTarefasAtribuirResponsavelCreateBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>, TError,{id: number;data: TasksTarefasAtribuirResponsavelCreateBody}, TContext> => {

const mutationKey = ['tasksTarefasAtribuirResponsavelCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>, {id: number;data: TasksTarefasAtribuirResponsavelCreateBody}> = (props) => {
          const {id,data} = props ?? {};

          return  tasksTarefasAtribuirResponsavelCreate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TasksTarefasAtribuirResponsavelCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>>
    export type TasksTarefasAtribuirResponsavelCreateMutationBody = TasksTarefasAtribuirResponsavelCreateBody
    export type TasksTarefasAtribuirResponsavelCreateMutationError = AxiosError<TasksTarefasAtribuirResponsavelCreate400 | TasksTarefasAtribuirResponsavelCreate404>

    /**
 * @summary Atribuir responsável à tarefa
 */
export const useTasksTarefasAtribuirResponsavelCreate = <TError = AxiosError<TasksTarefasAtribuirResponsavelCreate400 | TasksTarefasAtribuirResponsavelCreate404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>, TError,{id: number;data: TasksTarefasAtribuirResponsavelCreateBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof tasksTarefasAtribuirResponsavelCreate>>,
        TError,
        {id: number;data: TasksTarefasAtribuirResponsavelCreateBody},
        TContext
      > => {

      const mutationOptions = getTasksTarefasAtribuirResponsavelCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Remove um usuário como responsável pela tarefa.
 * @summary Remover responsável da tarefa
 */
export const tasksTarefasRemoverResponsavelCreate = (
    id: MaybeRef<number>,
    tasksTarefasRemoverResponsavelCreateBody: MaybeRef<TasksTarefasRemoverResponsavelCreateBody>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    id = unref(id);
tasksTarefasRemoverResponsavelCreateBody = unref(tasksTarefasRemoverResponsavelCreateBody);
    
    return axios.post(
      `/api/tasks/tarefas/${id}/remover_responsavel/`,
      tasksTarefasRemoverResponsavelCreateBody,options
    );
  }



export const getTasksTarefasRemoverResponsavelCreateMutationOptions = <TError = AxiosError<TasksTarefasRemoverResponsavelCreate400 | TasksTarefasRemoverResponsavelCreate404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>, TError,{id: number;data: TasksTarefasRemoverResponsavelCreateBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>, TError,{id: number;data: TasksTarefasRemoverResponsavelCreateBody}, TContext> => {

const mutationKey = ['tasksTarefasRemoverResponsavelCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>, {id: number;data: TasksTarefasRemoverResponsavelCreateBody}> = (props) => {
          const {id,data} = props ?? {};

          return  tasksTarefasRemoverResponsavelCreate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TasksTarefasRemoverResponsavelCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>>
    export type TasksTarefasRemoverResponsavelCreateMutationBody = TasksTarefasRemoverResponsavelCreateBody
    export type TasksTarefasRemoverResponsavelCreateMutationError = AxiosError<TasksTarefasRemoverResponsavelCreate400 | TasksTarefasRemoverResponsavelCreate404>

    /**
 * @summary Remover responsável da tarefa
 */
export const useTasksTarefasRemoverResponsavelCreate = <TError = AxiosError<TasksTarefasRemoverResponsavelCreate400 | TasksTarefasRemoverResponsavelCreate404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>, TError,{id: number;data: TasksTarefasRemoverResponsavelCreateBody}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof tasksTarefasRemoverResponsavelCreate>>,
        TError,
        {id: number;data: TasksTarefasRemoverResponsavelCreateBody},
        TContext
      > => {

      const mutationOptions = getTasksTarefasRemoverResponsavelCreateMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    