/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import axiosInstance from "../axios-instance";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  Activation,
  ActivationRequest,
  AuthUsersListParams,
  PaginatedUserList,
  PasswordResetConfirm,
  PasswordResetConfirmRequest,
  PatchedUserRequest,
  SendEmailReset,
  SendEmailResetRequest,
  SetPassword,
  SetPasswordRequest,
  SetUsername,
  SetUsernameRequest,
  TokenObtainPair,
  TokenObtainPairRequest,
  TokenRefresh,
  TokenRefreshRequest,
  TokenVerifyRequest,
  User,
  UserCreate,
  UserCreateRequest,
  UserRequest,
  UsernameResetConfirm,
  UsernameResetConfirmRequest,
} from ".././schemas";

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const authJwtCreateCreate = (
  tokenObtainPairRequest: MaybeRef<TokenObtainPairRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TokenObtainPair>> => {
  tokenObtainPairRequest = unref(tokenObtainPairRequest);

  return axiosInstance.post(
    `/api/auth/jwt/create/`,
    tokenObtainPairRequest,
    options
  );
};

export const getAuthJwtCreateCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authJwtCreateCreate>>,
    TError,
    { data: TokenObtainPairRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authJwtCreateCreate>>,
  TError,
  { data: TokenObtainPairRequest },
  TContext
> => {
  const mutationKey = ["authJwtCreateCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authJwtCreateCreate>>,
    { data: TokenObtainPairRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authJwtCreateCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthJwtCreateCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authJwtCreateCreate>>
>;
export type AuthJwtCreateCreateMutationBody = TokenObtainPairRequest;
export type AuthJwtCreateCreateMutationError = AxiosError<unknown>;

export const useAuthJwtCreateCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authJwtCreateCreate>>,
      TError,
      { data: TokenObtainPairRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authJwtCreateCreate>>,
  TError,
  { data: TokenObtainPairRequest },
  TContext
> => {
  const mutationOptions = getAuthJwtCreateCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authJwtRefreshCreate = (
  tokenRefreshRequest: MaybeRef<TokenRefreshRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TokenRefresh>> => {
  tokenRefreshRequest = unref(tokenRefreshRequest);

  return axiosInstance.post(
    `/api/auth/jwt/refresh/`,
    tokenRefreshRequest,
    options
  );
};

export const getAuthJwtRefreshCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authJwtRefreshCreate>>,
    TError,
    { data: TokenRefreshRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authJwtRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationKey = ["authJwtRefreshCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authJwtRefreshCreate>>,
    { data: TokenRefreshRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authJwtRefreshCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthJwtRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authJwtRefreshCreate>>
>;
export type AuthJwtRefreshCreateMutationBody = TokenRefreshRequest;
export type AuthJwtRefreshCreateMutationError = AxiosError<unknown>;

export const useAuthJwtRefreshCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authJwtRefreshCreate>>,
      TError,
      { data: TokenRefreshRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authJwtRefreshCreate>>,
  TError,
  { data: TokenRefreshRequest },
  TContext
> => {
  const mutationOptions = getAuthJwtRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Takes a token and indicates if it is valid.  This view provides no
information about a token's fitness for a particular use.
 */
export const authJwtVerifyCreate = (
  tokenVerifyRequest: MaybeRef<TokenVerifyRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  tokenVerifyRequest = unref(tokenVerifyRequest);

  return axiosInstance.post(
    `/api/auth/jwt/verify/`,
    tokenVerifyRequest,
    options
  );
};

export const getAuthJwtVerifyCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authJwtVerifyCreate>>,
    TError,
    { data: TokenVerifyRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authJwtVerifyCreate>>,
  TError,
  { data: TokenVerifyRequest },
  TContext
> => {
  const mutationKey = ["authJwtVerifyCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authJwtVerifyCreate>>,
    { data: TokenVerifyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authJwtVerifyCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthJwtVerifyCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authJwtVerifyCreate>>
>;
export type AuthJwtVerifyCreateMutationBody = TokenVerifyRequest;
export type AuthJwtVerifyCreateMutationError = AxiosError<unknown>;

export const useAuthJwtVerifyCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authJwtVerifyCreate>>,
      TError,
      { data: TokenVerifyRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authJwtVerifyCreate>>,
  TError,
  { data: TokenVerifyRequest },
  TContext
> => {
  const mutationOptions = getAuthJwtVerifyCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersList = (
  params?: MaybeRef<AuthUsersListParams>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PaginatedUserList>> => {
  params = unref(params);

  return axiosInstance.get(`/api/auth/users/`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  });
};

export const getAuthUsersListQueryKey = (
  params?: MaybeRef<AuthUsersListParams>
) => {
  return ["api", "auth", "users", ...(params ? [params] : [])] as const;
};

export const getAuthUsersListQueryOptions = <
  TData = Awaited<ReturnType<typeof authUsersList>>,
  TError = AxiosError<unknown>,
>(
  params?: MaybeRef<AuthUsersListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authUsersList>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getAuthUsersListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authUsersList>>> = ({
    signal,
  }) => authUsersList(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authUsersList>>,
    TError,
    TData
  >;
};

export type AuthUsersListQueryResult = NonNullable<
  Awaited<ReturnType<typeof authUsersList>>
>;
export type AuthUsersListQueryError = AxiosError<unknown>;

export function useAuthUsersList<
  TData = Awaited<ReturnType<typeof authUsersList>>,
  TError = AxiosError<unknown>,
>(
  params?: MaybeRef<AuthUsersListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authUsersList>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthUsersListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const authUsersCreate = (
  userCreateRequest: MaybeRef<UserCreateRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<UserCreate>> => {
  userCreateRequest = unref(userCreateRequest);

  return axiosInstance.post(`/api/auth/users/`, userCreateRequest, options);
};

export const getAuthUsersCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersCreate>>,
    TError,
    { data: UserCreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersCreate>>,
  TError,
  { data: UserCreateRequest },
  TContext
> => {
  const mutationKey = ["authUsersCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersCreate>>,
    { data: UserCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersCreate>>
>;
export type AuthUsersCreateMutationBody = UserCreateRequest;
export type AuthUsersCreateMutationError = AxiosError<unknown>;

export const useAuthUsersCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersCreate>>,
      TError,
      { data: UserCreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersCreate>>,
  TError,
  { data: UserCreateRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersRetrieve = (
  id: MaybeRef<number>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  id = unref(id);

  return axiosInstance.get(`/api/auth/users/${id}/`, options);
};

export const getAuthUsersRetrieveQueryKey = (id: MaybeRef<number>) => {
  return ["api", "auth", "users", id] as const;
};

export const getAuthUsersRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof authUsersRetrieve>>,
  TError = AxiosError<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUsersRetrieve>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getAuthUsersRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authUsersRetrieve>>
  > = ({ signal }) => authUsersRetrieve(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof authUsersRetrieve>>,
    TError,
    TData
  >;
};

export type AuthUsersRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof authUsersRetrieve>>
>;
export type AuthUsersRetrieveQueryError = AxiosError<unknown>;

export function useAuthUsersRetrieve<
  TData = Awaited<ReturnType<typeof authUsersRetrieve>>,
  TError = AxiosError<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUsersRetrieve>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthUsersRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const authUsersUpdate = (
  id: MaybeRef<number>,
  userRequest: MaybeRef<UserRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  id = unref(id);
  userRequest = unref(userRequest);

  return axiosInstance.put(`/api/auth/users/${id}/`, userRequest, options);
};

export const getAuthUsersUpdateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersUpdate>>,
    TError,
    { id: number; data: UserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersUpdate>>,
  TError,
  { id: number; data: UserRequest },
  TContext
> => {
  const mutationKey = ["authUsersUpdate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersUpdate>>,
    { id: number; data: UserRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return authUsersUpdate(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersUpdate>>
>;
export type AuthUsersUpdateMutationBody = UserRequest;
export type AuthUsersUpdateMutationError = AxiosError<unknown>;

export const useAuthUsersUpdate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersUpdate>>,
      TError,
      { id: number; data: UserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersUpdate>>,
  TError,
  { id: number; data: UserRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersPartialUpdate = (
  id: MaybeRef<number>,
  patchedUserRequest: MaybeRef<PatchedUserRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  id = unref(id);
  patchedUserRequest = unref(patchedUserRequest);

  return axiosInstance.patch(
    `/api/auth/users/${id}/`,
    patchedUserRequest,
    options
  );
};

export const getAuthUsersPartialUpdateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersPartialUpdate>>,
    TError,
    { id: number; data: PatchedUserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersPartialUpdate>>,
  TError,
  { id: number; data: PatchedUserRequest },
  TContext
> => {
  const mutationKey = ["authUsersPartialUpdate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersPartialUpdate>>,
    { id: number; data: PatchedUserRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return authUsersPartialUpdate(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersPartialUpdate>>
>;
export type AuthUsersPartialUpdateMutationBody = PatchedUserRequest;
export type AuthUsersPartialUpdateMutationError = AxiosError<unknown>;

export const useAuthUsersPartialUpdate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersPartialUpdate>>,
      TError,
      { id: number; data: PatchedUserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersPartialUpdate>>,
  TError,
  { id: number; data: PatchedUserRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersDestroy = (
  id: MaybeRef<number>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  id = unref(id);

  return axiosInstance.delete(`/api/auth/users/${id}/`, options);
};

export const getAuthUsersDestroyMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersDestroy>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["authUsersDestroy"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return authUsersDestroy(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersDestroy>>
>;

export type AuthUsersDestroyMutationError = AxiosError<unknown>;

export const useAuthUsersDestroy = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersDestroy>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getAuthUsersDestroyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersActivationCreate = (
  activationRequest: MaybeRef<ActivationRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Activation>> => {
  activationRequest = unref(activationRequest);

  return axiosInstance.post(
    `/api/auth/users/activation/`,
    activationRequest,
    options
  );
};

export const getAuthUsersActivationCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersActivationCreate>>,
    TError,
    { data: ActivationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersActivationCreate>>,
  TError,
  { data: ActivationRequest },
  TContext
> => {
  const mutationKey = ["authUsersActivationCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersActivationCreate>>,
    { data: ActivationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersActivationCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersActivationCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersActivationCreate>>
>;
export type AuthUsersActivationCreateMutationBody = ActivationRequest;
export type AuthUsersActivationCreateMutationError = AxiosError<unknown>;

export const useAuthUsersActivationCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersActivationCreate>>,
      TError,
      { data: ActivationRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersActivationCreate>>,
  TError,
  { data: ActivationRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersActivationCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersMeRetrieve = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  return axiosInstance.get(`/api/auth/users/me/`, options);
};

export const getAuthUsersMeRetrieveQueryKey = () => {
  return ["api", "auth", "users", "me"] as const;
};

export const getAuthUsersMeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof authUsersMeRetrieve>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authUsersMeRetrieve>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getAuthUsersMeRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authUsersMeRetrieve>>
  > = ({ signal }) => authUsersMeRetrieve({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authUsersMeRetrieve>>,
    TError,
    TData
  >;
};

export type AuthUsersMeRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof authUsersMeRetrieve>>
>;
export type AuthUsersMeRetrieveQueryError = AxiosError<unknown>;

export function useAuthUsersMeRetrieve<
  TData = Awaited<ReturnType<typeof authUsersMeRetrieve>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authUsersMeRetrieve>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthUsersMeRetrieveQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const authUsersMeUpdate = (
  userRequest: MaybeRef<UserRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  userRequest = unref(userRequest);

  return axiosInstance.put(`/api/auth/users/me/`, userRequest, options);
};

export const getAuthUsersMeUpdateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersMeUpdate>>,
    TError,
    { data: UserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersMeUpdate>>,
  TError,
  { data: UserRequest },
  TContext
> => {
  const mutationKey = ["authUsersMeUpdate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersMeUpdate>>,
    { data: UserRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersMeUpdate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersMeUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersMeUpdate>>
>;
export type AuthUsersMeUpdateMutationBody = UserRequest;
export type AuthUsersMeUpdateMutationError = AxiosError<unknown>;

export const useAuthUsersMeUpdate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersMeUpdate>>,
      TError,
      { data: UserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersMeUpdate>>,
  TError,
  { data: UserRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersMeUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersMePartialUpdate = (
  patchedUserRequest: MaybeRef<PatchedUserRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<User>> => {
  patchedUserRequest = unref(patchedUserRequest);

  return axiosInstance.patch(
    `/api/auth/users/me/`,
    patchedUserRequest,
    options
  );
};

export const getAuthUsersMePartialUpdateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersMePartialUpdate>>,
    TError,
    { data: PatchedUserRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersMePartialUpdate>>,
  TError,
  { data: PatchedUserRequest },
  TContext
> => {
  const mutationKey = ["authUsersMePartialUpdate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersMePartialUpdate>>,
    { data: PatchedUserRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersMePartialUpdate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersMePartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersMePartialUpdate>>
>;
export type AuthUsersMePartialUpdateMutationBody = PatchedUserRequest;
export type AuthUsersMePartialUpdateMutationError = AxiosError<unknown>;

export const useAuthUsersMePartialUpdate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersMePartialUpdate>>,
      TError,
      { data: PatchedUserRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersMePartialUpdate>>,
  TError,
  { data: PatchedUserRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersMePartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersMeDestroy = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<void>> => {
  return axiosInstance.delete(`/api/auth/users/me/`, options);
};

export const getAuthUsersMeDestroyMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersMeDestroy>>,
    TError,
    void,
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersMeDestroy>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authUsersMeDestroy"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersMeDestroy>>,
    void
  > = () => {
    return authUsersMeDestroy(axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersMeDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersMeDestroy>>
>;

export type AuthUsersMeDestroyMutationError = AxiosError<unknown>;

export const useAuthUsersMeDestroy = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersMeDestroy>>,
      TError,
      void,
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersMeDestroy>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getAuthUsersMeDestroyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersResendActivationCreate = (
  sendEmailResetRequest: MaybeRef<SendEmailResetRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SendEmailReset>> => {
  sendEmailResetRequest = unref(sendEmailResetRequest);

  return axiosInstance.post(
    `/api/auth/users/resend_activation/`,
    sendEmailResetRequest,
    options
  );
};

export const getAuthUsersResendActivationCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersResendActivationCreate>>,
    TError,
    { data: SendEmailResetRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersResendActivationCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationKey = ["authUsersResendActivationCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersResendActivationCreate>>,
    { data: SendEmailResetRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersResendActivationCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersResendActivationCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersResendActivationCreate>>
>;
export type AuthUsersResendActivationCreateMutationBody = SendEmailResetRequest;
export type AuthUsersResendActivationCreateMutationError = AxiosError<unknown>;

export const useAuthUsersResendActivationCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersResendActivationCreate>>,
      TError,
      { data: SendEmailResetRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersResendActivationCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationOptions =
    getAuthUsersResendActivationCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersResetPasswordCreate = (
  sendEmailResetRequest: MaybeRef<SendEmailResetRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SendEmailReset>> => {
  sendEmailResetRequest = unref(sendEmailResetRequest);

  return axiosInstance.post(
    `/api/auth/users/reset_password/`,
    sendEmailResetRequest,
    options
  );
};

export const getAuthUsersResetPasswordCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersResetPasswordCreate>>,
    TError,
    { data: SendEmailResetRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersResetPasswordCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationKey = ["authUsersResetPasswordCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersResetPasswordCreate>>,
    { data: SendEmailResetRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersResetPasswordCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersResetPasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersResetPasswordCreate>>
>;
export type AuthUsersResetPasswordCreateMutationBody = SendEmailResetRequest;
export type AuthUsersResetPasswordCreateMutationError = AxiosError<unknown>;

export const useAuthUsersResetPasswordCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersResetPasswordCreate>>,
      TError,
      { data: SendEmailResetRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersResetPasswordCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationOptions =
    getAuthUsersResetPasswordCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersResetPasswordConfirmCreate = (
  passwordResetConfirmRequest: MaybeRef<PasswordResetConfirmRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<PasswordResetConfirm>> => {
  passwordResetConfirmRequest = unref(passwordResetConfirmRequest);

  return axiosInstance.post(
    `/api/auth/users/reset_password_confirm/`,
    passwordResetConfirmRequest,
    options
  );
};

export const getAuthUsersResetPasswordConfirmCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>,
    TError,
    { data: PasswordResetConfirmRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>,
  TError,
  { data: PasswordResetConfirmRequest },
  TContext
> => {
  const mutationKey = ["authUsersResetPasswordConfirmCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>,
    { data: PasswordResetConfirmRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersResetPasswordConfirmCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersResetPasswordConfirmCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>
>;
export type AuthUsersResetPasswordConfirmCreateMutationBody =
  PasswordResetConfirmRequest;
export type AuthUsersResetPasswordConfirmCreateMutationError =
  AxiosError<unknown>;

export const useAuthUsersResetPasswordConfirmCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>,
      TError,
      { data: PasswordResetConfirmRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersResetPasswordConfirmCreate>>,
  TError,
  { data: PasswordResetConfirmRequest },
  TContext
> => {
  const mutationOptions =
    getAuthUsersResetPasswordConfirmCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersResetUsernameCreate = (
  sendEmailResetRequest: MaybeRef<SendEmailResetRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SendEmailReset>> => {
  sendEmailResetRequest = unref(sendEmailResetRequest);

  return axiosInstance.post(
    `/api/auth/users/reset_username/`,
    sendEmailResetRequest,
    options
  );
};

export const getAuthUsersResetUsernameCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersResetUsernameCreate>>,
    TError,
    { data: SendEmailResetRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersResetUsernameCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationKey = ["authUsersResetUsernameCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersResetUsernameCreate>>,
    { data: SendEmailResetRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersResetUsernameCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersResetUsernameCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersResetUsernameCreate>>
>;
export type AuthUsersResetUsernameCreateMutationBody = SendEmailResetRequest;
export type AuthUsersResetUsernameCreateMutationError = AxiosError<unknown>;

export const useAuthUsersResetUsernameCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersResetUsernameCreate>>,
      TError,
      { data: SendEmailResetRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersResetUsernameCreate>>,
  TError,
  { data: SendEmailResetRequest },
  TContext
> => {
  const mutationOptions =
    getAuthUsersResetUsernameCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersResetUsernameConfirmCreate = (
  usernameResetConfirmRequest: MaybeRef<UsernameResetConfirmRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<UsernameResetConfirm>> => {
  usernameResetConfirmRequest = unref(usernameResetConfirmRequest);

  return axiosInstance.post(
    `/api/auth/users/reset_username_confirm/`,
    usernameResetConfirmRequest,
    options
  );
};

export const getAuthUsersResetUsernameConfirmCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>,
    TError,
    { data: UsernameResetConfirmRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>,
  TError,
  { data: UsernameResetConfirmRequest },
  TContext
> => {
  const mutationKey = ["authUsersResetUsernameConfirmCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>,
    { data: UsernameResetConfirmRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersResetUsernameConfirmCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersResetUsernameConfirmCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>
>;
export type AuthUsersResetUsernameConfirmCreateMutationBody =
  UsernameResetConfirmRequest;
export type AuthUsersResetUsernameConfirmCreateMutationError =
  AxiosError<unknown>;

export const useAuthUsersResetUsernameConfirmCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>,
      TError,
      { data: UsernameResetConfirmRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersResetUsernameConfirmCreate>>,
  TError,
  { data: UsernameResetConfirmRequest },
  TContext
> => {
  const mutationOptions =
    getAuthUsersResetUsernameConfirmCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersSetPasswordCreate = (
  setPasswordRequest: MaybeRef<SetPasswordRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SetPassword>> => {
  setPasswordRequest = unref(setPasswordRequest);

  return axiosInstance.post(
    `/api/auth/users/set_password/`,
    setPasswordRequest,
    options
  );
};

export const getAuthUsersSetPasswordCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersSetPasswordCreate>>,
    TError,
    { data: SetPasswordRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersSetPasswordCreate>>,
  TError,
  { data: SetPasswordRequest },
  TContext
> => {
  const mutationKey = ["authUsersSetPasswordCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersSetPasswordCreate>>,
    { data: SetPasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersSetPasswordCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersSetPasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersSetPasswordCreate>>
>;
export type AuthUsersSetPasswordCreateMutationBody = SetPasswordRequest;
export type AuthUsersSetPasswordCreateMutationError = AxiosError<unknown>;

export const useAuthUsersSetPasswordCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersSetPasswordCreate>>,
      TError,
      { data: SetPasswordRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersSetPasswordCreate>>,
  TError,
  { data: SetPasswordRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersSetPasswordCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const authUsersSetUsernameCreate = (
  setUsernameRequest: MaybeRef<SetUsernameRequest>,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<SetUsername>> => {
  setUsernameRequest = unref(setUsernameRequest);

  return axiosInstance.post(
    `/api/auth/users/set_username/`,
    setUsernameRequest,
    options
  );
};

export const getAuthUsersSetUsernameCreateMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authUsersSetUsernameCreate>>,
    TError,
    { data: SetUsernameRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authUsersSetUsernameCreate>>,
  TError,
  { data: SetUsernameRequest },
  TContext
> => {
  const mutationKey = ["authUsersSetUsernameCreate"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authUsersSetUsernameCreate>>,
    { data: SetUsernameRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authUsersSetUsernameCreate(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthUsersSetUsernameCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authUsersSetUsernameCreate>>
>;
export type AuthUsersSetUsernameCreateMutationBody = SetUsernameRequest;
export type AuthUsersSetUsernameCreateMutationError = AxiosError<unknown>;

export const useAuthUsersSetUsernameCreate = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authUsersSetUsernameCreate>>,
      TError,
      { data: SetUsernameRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof authUsersSetUsernameCreate>>,
  TError,
  { data: SetUsernameRequest },
  TContext
> => {
  const mutationOptions = getAuthUsersSetUsernameCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
