/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  AtribuicaoTarefa,
  ComentarioTarefa,
  PaginatedHistoricoStatusTarefaList,
  PaginatedTarefaListList,
  PatchedTarefaRequest,
  Tarefa,
  TarefaRequest,
  TasksAddCommentRequest,
  TasksAssignUserRequest,
  TasksAssociarSprintRequest,
  TasksTarefasListParams,
  TasksTarefasStatusHistoryListParams,
  TasksUpdateStatusRequest,
} from ".././schemas";

import { customMutator } from "../../lib/axios-instance";
import type { ErrorType } from "../../lib/axios-instance";

/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Listar Tarefas
 */
export const tasksTarefasList = (
  params?: MaybeRef<TasksTarefasListParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customMutator<PaginatedTarefaListList>({
    url: `/api/tasks/tarefas/`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getTasksTarefasListQueryKey = (
  params?: MaybeRef<TasksTarefasListParams>,
) => {
  return ["api", "tasks", "tarefas", ...(params ? [params] : [])] as const;
};

export const getTasksTarefasListQueryOptions = <
  TData = Awaited<ReturnType<typeof tasksTarefasList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<TasksTarefasListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getTasksTarefasListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksTarefasList>>
  > = ({ signal }) => tasksTarefasList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tasksTarefasList>>,
    TError,
    TData
  >;
};

export type TasksTarefasListQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasList>>
>;
export type TasksTarefasListQueryError = ErrorType<unknown>;

/**
 * @summary Listar Tarefas
 */

export function useTasksTarefasList<
  TData = Awaited<ReturnType<typeof tasksTarefasList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<TasksTarefasListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTasksTarefasListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Criar Tarefa
 */
export const tasksTarefasCreate = (
  tarefaRequest: MaybeRef<TarefaRequest>,
  signal?: AbortSignal,
) => {
  tarefaRequest = unref(tarefaRequest);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tarefaRequest,
    signal,
  });
};

export const getTasksTarefasCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasCreate>>,
    TError,
    { data: TarefaRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasCreate>>,
  TError,
  { data: TarefaRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasCreate>>,
    { data: TarefaRequest }
  > = (props) => {
    const { data } = props ?? {};

    return tasksTarefasCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasCreate>>
>;
export type TasksTarefasCreateMutationBody = TarefaRequest;
export type TasksTarefasCreateMutationError = ErrorType<unknown>;

/**
 * @summary Criar Tarefa
 */
export const useTasksTarefasCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasCreate>>,
      TError,
      { data: TarefaRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasCreate>>,
  TError,
  { data: TarefaRequest },
  TContext
> => {
  const mutationOptions = getTasksTarefasCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Obter Tarefa
 */
export const tasksTarefasRetrieve = (
  id: MaybeRef<number>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/${id}/`,
    method: "GET",
    signal,
  });
};

export const getTasksTarefasRetrieveQueryKey = (id: MaybeRef<number>) => {
  return ["api", "tasks", "tarefas", id] as const;
};

export const getTasksTarefasRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof tasksTarefasRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getTasksTarefasRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksTarefasRetrieve>>
  > = ({ signal }) => tasksTarefasRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof tasksTarefasRetrieve>>,
    TError,
    TData
  >;
};

export type TasksTarefasRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasRetrieve>>
>;
export type TasksTarefasRetrieveQueryError = ErrorType<unknown>;

/**
 * @summary Obter Tarefa
 */

export function useTasksTarefasRetrieve<
  TData = Awaited<ReturnType<typeof tasksTarefasRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTasksTarefasRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Atualizar Tarefa (Completo)
 */
export const tasksTarefasUpdate = (
  id: MaybeRef<number>,
  tarefaRequest: MaybeRef<TarefaRequest>,
) => {
  id = unref(id);
  tarefaRequest = unref(tarefaRequest);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/${id}/`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: tarefaRequest,
  });
};

export const getTasksTarefasUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasUpdate>>,
    TError,
    { id: number; data: TarefaRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasUpdate>>,
  TError,
  { id: number; data: TarefaRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasUpdate>>,
    { id: number; data: TarefaRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasUpdate>>
>;
export type TasksTarefasUpdateMutationBody = TarefaRequest;
export type TasksTarefasUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar Tarefa (Completo)
 */
export const useTasksTarefasUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasUpdate>>,
      TError,
      { id: number; data: TarefaRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasUpdate>>,
  TError,
  { id: number; data: TarefaRequest },
  TContext
> => {
  const mutationOptions = getTasksTarefasUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Atualizar Tarefa (Parcial)
 */
export const tasksTarefasPartialUpdate = (
  id: MaybeRef<number>,
  patchedTarefaRequest: MaybeRef<PatchedTarefaRequest>,
) => {
  id = unref(id);
  patchedTarefaRequest = unref(patchedTarefaRequest);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/${id}/`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedTarefaRequest,
  });
};

export const getTasksTarefasPartialUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>,
    TError,
    { id: number; data: PatchedTarefaRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>,
  TError,
  { id: number; data: PatchedTarefaRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>,
    { id: number; data: PatchedTarefaRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>
>;
export type TasksTarefasPartialUpdateMutationBody = PatchedTarefaRequest;
export type TasksTarefasPartialUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar Tarefa (Parcial)
 */
export const useTasksTarefasPartialUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>,
      TError,
      { id: number; data: PatchedTarefaRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasPartialUpdate>>,
  TError,
  { id: number; data: PatchedTarefaRequest },
  TContext
> => {
  const mutationOptions = getTasksTarefasPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Excluir Tarefa
 */
export const tasksTarefasDestroy = (id: MaybeRef<number>) => {
  id = unref(id);

  return customMutator<void>({
    url: `/api/tasks/tarefas/${id}/`,
    method: "DELETE",
  });
};

export const getTasksTarefasDestroyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["tasksTarefasDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return tasksTarefasDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasDestroy>>
>;

export type TasksTarefasDestroyMutationError = ErrorType<unknown>;

/**
 * @summary Excluir Tarefa
 */
export const useTasksTarefasDestroy = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasDestroy>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getTasksTarefasDestroyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Adicionar comentário
 */
export const tasksTarefasAddCommentCreate = (
  id: MaybeRef<number>,
  tasksAddCommentRequest: MaybeRef<TasksAddCommentRequest>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  tasksAddCommentRequest = unref(tasksAddCommentRequest);

  return customMutator<ComentarioTarefa>({
    url: `/api/tasks/tarefas/${id}/add-comment/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tasksAddCommentRequest,
    signal,
  });
};

export const getTasksTarefasAddCommentCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>,
    TError,
    { id: number; data: TasksAddCommentRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>,
  TError,
  { id: number; data: TasksAddCommentRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasAddCommentCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>,
    { id: number; data: TasksAddCommentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasAddCommentCreate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasAddCommentCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>
>;
export type TasksTarefasAddCommentCreateMutationBody = TasksAddCommentRequest;
export type TasksTarefasAddCommentCreateMutationError = ErrorType<unknown>;

/**
 * @summary Adicionar comentário
 */
export const useTasksTarefasAddCommentCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>,
      TError,
      { id: number; data: TasksAddCommentRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasAddCommentCreate>>,
  TError,
  { id: number; data: TasksAddCommentRequest },
  TContext
> => {
  const mutationOptions =
    getTasksTarefasAddCommentCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Atribuir responsável
 */
export const tasksTarefasAssignUserCreate = (
  id: MaybeRef<number>,
  tasksAssignUserRequest: MaybeRef<TasksAssignUserRequest>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  tasksAssignUserRequest = unref(tasksAssignUserRequest);

  return customMutator<AtribuicaoTarefa>({
    url: `/api/tasks/tarefas/${id}/assign-user/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tasksAssignUserRequest,
    signal,
  });
};

export const getTasksTarefasAssignUserCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>,
    TError,
    { id: number; data: TasksAssignUserRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>,
  TError,
  { id: number; data: TasksAssignUserRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasAssignUserCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>,
    { id: number; data: TasksAssignUserRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasAssignUserCreate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasAssignUserCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>
>;
export type TasksTarefasAssignUserCreateMutationBody = TasksAssignUserRequest;
export type TasksTarefasAssignUserCreateMutationError = ErrorType<unknown>;

/**
 * @summary Atribuir responsável
 */
export const useTasksTarefasAssignUserCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>,
      TError,
      { id: number; data: TasksAssignUserRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasAssignUserCreate>>,
  TError,
  { id: number; data: TasksAssignUserRequest },
  TContext
> => {
  const mutationOptions =
    getTasksTarefasAssignUserCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Associar a uma sprint
 */
export const tasksTarefasAssociateSprintCreate = (
  id: MaybeRef<number>,
  tasksAssociarSprintRequest: MaybeRef<TasksAssociarSprintRequest>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  tasksAssociarSprintRequest = unref(tasksAssociarSprintRequest);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/${id}/associate-sprint/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tasksAssociarSprintRequest,
    signal,
  });
};

export const getTasksTarefasAssociateSprintCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>,
    TError,
    { id: number; data: TasksAssociarSprintRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>,
  TError,
  { id: number; data: TasksAssociarSprintRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasAssociateSprintCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>,
    { id: number; data: TasksAssociarSprintRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasAssociateSprintCreate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasAssociateSprintCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>
>;
export type TasksTarefasAssociateSprintCreateMutationBody =
  TasksAssociarSprintRequest;
export type TasksTarefasAssociateSprintCreateMutationError = ErrorType<unknown>;

/**
 * @summary Associar a uma sprint
 */
export const useTasksTarefasAssociateSprintCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>,
      TError,
      { id: number; data: TasksAssociarSprintRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasAssociateSprintCreate>>,
  TError,
  { id: number; data: TasksAssociarSprintRequest },
  TContext
> => {
  const mutationOptions =
    getTasksTarefasAssociateSprintCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Obter histórico de status
 */
export const tasksTarefasStatusHistoryList = (
  id: MaybeRef<number>,
  params?: MaybeRef<TasksTarefasStatusHistoryListParams>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  params = unref(params);

  return customMutator<PaginatedHistoricoStatusTarefaList>({
    url: `/api/tasks/tarefas/${id}/status-history/`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getTasksTarefasStatusHistoryListQueryKey = (
  id: MaybeRef<number>,
  params?: MaybeRef<TasksTarefasStatusHistoryListParams>,
) => {
  return [
    "api",
    "tasks",
    "tarefas",
    id,
    "status-history",
    ...(params ? [params] : []),
  ] as const;
};

export const getTasksTarefasStatusHistoryListQueryOptions = <
  TData = Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  params?: MaybeRef<TasksTarefasStatusHistoryListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getTasksTarefasStatusHistoryListQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>
  > = ({ signal }) => tasksTarefasStatusHistoryList(id, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>,
    TError,
    TData
  >;
};

export type TasksTarefasStatusHistoryListQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>
>;
export type TasksTarefasStatusHistoryListQueryError = ErrorType<unknown>;

/**
 * @summary Obter histórico de status
 */

export function useTasksTarefasStatusHistoryList<
  TData = Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  params?: MaybeRef<TasksTarefasStatusHistoryListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksTarefasStatusHistoryList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTasksTarefasStatusHistoryListQueryOptions(
    id,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Remover responsável
 */
export const tasksTarefasUnassignUserCreate = (
  id: MaybeRef<number>,
  tasksAssignUserRequest: MaybeRef<TasksAssignUserRequest>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  tasksAssignUserRequest = unref(tasksAssignUserRequest);

  return customMutator<void>({
    url: `/api/tasks/tarefas/${id}/unassign-user/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tasksAssignUserRequest,
    signal,
  });
};

export const getTasksTarefasUnassignUserCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>,
    TError,
    { id: number; data: TasksAssignUserRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>,
  TError,
  { id: number; data: TasksAssignUserRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasUnassignUserCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>,
    { id: number; data: TasksAssignUserRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasUnassignUserCreate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasUnassignUserCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>
>;
export type TasksTarefasUnassignUserCreateMutationBody = TasksAssignUserRequest;
export type TasksTarefasUnassignUserCreateMutationError = ErrorType<void>;

/**
 * @summary Remover responsável
 */
export const useTasksTarefasUnassignUserCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>,
      TError,
      { id: number; data: TasksAssignUserRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasUnassignUserCreate>>,
  TError,
  { id: number; data: TasksAssignUserRequest },
  TContext
> => {
  const mutationOptions =
    getTasksTarefasUnassignUserCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Endpoint para gerenciar Tarefas, suas atribuições, comentários e status.
Fornece filtragem avançada através de parâmetros de query.
 * @summary Atualizar status
 */
export const tasksTarefasUpdateStatusCreate = (
  id: MaybeRef<number>,
  tasksUpdateStatusRequest: MaybeRef<TasksUpdateStatusRequest>,
  signal?: AbortSignal,
) => {
  id = unref(id);
  tasksUpdateStatusRequest = unref(tasksUpdateStatusRequest);

  return customMutator<Tarefa>({
    url: `/api/tasks/tarefas/${id}/update-status/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: tasksUpdateStatusRequest,
    signal,
  });
};

export const getTasksTarefasUpdateStatusCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>,
    TError,
    { id: number; data: TasksUpdateStatusRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>,
  TError,
  { id: number; data: TasksUpdateStatusRequest },
  TContext
> => {
  const mutationKey = ["tasksTarefasUpdateStatusCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>,
    { id: number; data: TasksUpdateStatusRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksTarefasUpdateStatusCreate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksTarefasUpdateStatusCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>
>;
export type TasksTarefasUpdateStatusCreateMutationBody =
  TasksUpdateStatusRequest;
export type TasksTarefasUpdateStatusCreateMutationError = ErrorType<unknown>;

/**
 * @summary Atualizar status
 */
export const useTasksTarefasUpdateStatusCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>,
      TError,
      { id: number; data: TasksUpdateStatusRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tasksTarefasUpdateStatusCreate>>,
  TError,
  { id: number; data: TasksUpdateStatusRequest },
  TContext
> => {
  const mutationOptions =
    getTasksTarefasUpdateStatusCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
