# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('projects', '0003_historicostatusprojeto_tenant_membroprojeto_tenant_and_more'),
        ('tasks', '0002_tarefa_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicaotarefa',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentariotarefa',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicostatustarefa',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comentariotarefa',
            index=models.Index(fields=['tenant', '-criado_em'], name='tasks_comen_tenant__d4c062_idx'),
        ),
        migrations.AddIndex(
            model_name='historicostatustarefa',
            index=models.Index(fields=['tenant', '-alterado_em'], name='tasks_histo_tenant__a2f50d_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['tenant', 'prioridade', 'data_termino'], name='tasks_taref_tenant__080080_idx'),
        ),
    ]
