/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  CommunicationsListParams,
  Comunicacao,
  ComunicacaoRequest,
  PaginatedComunicacaoList,
  PatchedComunicacaoRequest,
} from ".././schemas";

import { customMutator } from "../../lib/axios-instance";
import type { ErrorType } from "../../lib/axios-instance";

/**
 * ViewSet para gerenciamento de comunicações formais.

Permite criar, listar, atualizar e excluir comunicações formais em projetos.
Comunicações formais são documentos oficiais como atas, memorandos e relatórios.

Endpoints:
- GET /comunicacoes/ - Lista todas as comunicações (com filtros)
- POST /comunicacoes/ - Cria uma nova comunicação
- GET /comunicacoes/{id}/ - Obtém detalhes de uma comunicação
- PUT/PATCH /comunicacoes/{id}/ - Atualiza uma comunicação
- DELETE /comunicacoes/{id}/ - Remove uma comunicação
 */
export const communicationsList = (
  params?: MaybeRef<CommunicationsListParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return customMutator<PaginatedComunicacaoList>({
    url: `/api/communications/`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getCommunicationsListQueryKey = (
  params?: MaybeRef<CommunicationsListParams>,
) => {
  return ["api", "communications", ...(params ? [params] : [])] as const;
};

export const getCommunicationsListQueryOptions = <
  TData = Awaited<ReturnType<typeof communicationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<CommunicationsListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communicationsList>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getCommunicationsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof communicationsList>>
  > = ({ signal }) => communicationsList(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof communicationsList>>,
    TError,
    TData
  >;
};

export type CommunicationsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof communicationsList>>
>;
export type CommunicationsListQueryError = ErrorType<unknown>;

export function useCommunicationsList<
  TData = Awaited<ReturnType<typeof communicationsList>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<CommunicationsListParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communicationsList>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommunicationsListQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * ViewSet para gerenciamento de comunicações formais.

Permite criar, listar, atualizar e excluir comunicações formais em projetos.
Comunicações formais são documentos oficiais como atas, memorandos e relatórios.

Endpoints:
- GET /comunicacoes/ - Lista todas as comunicações (com filtros)
- POST /comunicacoes/ - Cria uma nova comunicação
- GET /comunicacoes/{id}/ - Obtém detalhes de uma comunicação
- PUT/PATCH /comunicacoes/{id}/ - Atualiza uma comunicação
- DELETE /comunicacoes/{id}/ - Remove uma comunicação
 */
export const communicationsCreate = (
  comunicacaoRequest: MaybeRef<ComunicacaoRequest>,
  signal?: AbortSignal,
) => {
  comunicacaoRequest = unref(comunicacaoRequest);

  return customMutator<Comunicacao>({
    url: `/api/communications/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: comunicacaoRequest,
    signal,
  });
};

export const getCommunicationsCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communicationsCreate>>,
    TError,
    { data: ComunicacaoRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communicationsCreate>>,
  TError,
  { data: ComunicacaoRequest },
  TContext
> => {
  const mutationKey = ["communicationsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communicationsCreate>>,
    { data: ComunicacaoRequest }
  > = (props) => {
    const { data } = props ?? {};

    return communicationsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunicationsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof communicationsCreate>>
>;
export type CommunicationsCreateMutationBody = ComunicacaoRequest;
export type CommunicationsCreateMutationError = ErrorType<unknown>;

export const useCommunicationsCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof communicationsCreate>>,
      TError,
      { data: ComunicacaoRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof communicationsCreate>>,
  TError,
  { data: ComunicacaoRequest },
  TContext
> => {
  const mutationOptions = getCommunicationsCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * ViewSet para gerenciamento de comunicações formais.

Permite criar, listar, atualizar e excluir comunicações formais em projetos.
Comunicações formais são documentos oficiais como atas, memorandos e relatórios.

Endpoints:
- GET /comunicacoes/ - Lista todas as comunicações (com filtros)
- POST /comunicacoes/ - Cria uma nova comunicação
- GET /comunicacoes/{id}/ - Obtém detalhes de uma comunicação
- PUT/PATCH /comunicacoes/{id}/ - Atualiza uma comunicação
- DELETE /comunicacoes/{id}/ - Remove uma comunicação
 */
export const communicationsRetrieve = (
  id: MaybeRef<number>,
  signal?: AbortSignal,
) => {
  id = unref(id);

  return customMutator<Comunicacao>({
    url: `/api/communications/${id}/`,
    method: "GET",
    signal,
  });
};

export const getCommunicationsRetrieveQueryKey = (id: MaybeRef<number>) => {
  return ["api", "communications", id] as const;
};

export const getCommunicationsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof communicationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communicationsRetrieve>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getCommunicationsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof communicationsRetrieve>>
  > = ({ signal }) => communicationsRetrieve(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof communicationsRetrieve>>,
    TError,
    TData
  >;
};

export type CommunicationsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof communicationsRetrieve>>
>;
export type CommunicationsRetrieveQueryError = ErrorType<unknown>;

export function useCommunicationsRetrieve<
  TData = Awaited<ReturnType<typeof communicationsRetrieve>>,
  TError = ErrorType<unknown>,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof communicationsRetrieve>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCommunicationsRetrieveQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Sobrescreve o método de atualização para verificar permissões.

Apenas o remetente original ou um administrador pode atualizar uma comunicação.

Args:
    request: Objeto de requisição

Returns:
    Response: Resposta da atualização ou erro de permissão
 */
export const communicationsUpdate = (
  id: MaybeRef<number>,
  comunicacaoRequest: MaybeRef<ComunicacaoRequest>,
) => {
  id = unref(id);
  comunicacaoRequest = unref(comunicacaoRequest);

  return customMutator<Comunicacao>({
    url: `/api/communications/${id}/`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: comunicacaoRequest,
  });
};

export const getCommunicationsUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communicationsUpdate>>,
    TError,
    { id: number; data: ComunicacaoRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communicationsUpdate>>,
  TError,
  { id: number; data: ComunicacaoRequest },
  TContext
> => {
  const mutationKey = ["communicationsUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communicationsUpdate>>,
    { id: number; data: ComunicacaoRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return communicationsUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunicationsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof communicationsUpdate>>
>;
export type CommunicationsUpdateMutationBody = ComunicacaoRequest;
export type CommunicationsUpdateMutationError = ErrorType<unknown>;

export const useCommunicationsUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof communicationsUpdate>>,
      TError,
      { id: number; data: ComunicacaoRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof communicationsUpdate>>,
  TError,
  { id: number; data: ComunicacaoRequest },
  TContext
> => {
  const mutationOptions = getCommunicationsUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * ViewSet para gerenciamento de comunicações formais.

Permite criar, listar, atualizar e excluir comunicações formais em projetos.
Comunicações formais são documentos oficiais como atas, memorandos e relatórios.

Endpoints:
- GET /comunicacoes/ - Lista todas as comunicações (com filtros)
- POST /comunicacoes/ - Cria uma nova comunicação
- GET /comunicacoes/{id}/ - Obtém detalhes de uma comunicação
- PUT/PATCH /comunicacoes/{id}/ - Atualiza uma comunicação
- DELETE /comunicacoes/{id}/ - Remove uma comunicação
 */
export const communicationsPartialUpdate = (
  id: MaybeRef<number>,
  patchedComunicacaoRequest: MaybeRef<PatchedComunicacaoRequest>,
) => {
  id = unref(id);
  patchedComunicacaoRequest = unref(patchedComunicacaoRequest);

  return customMutator<Comunicacao>({
    url: `/api/communications/${id}/`,
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    data: patchedComunicacaoRequest,
  });
};

export const getCommunicationsPartialUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communicationsPartialUpdate>>,
    TError,
    { id: number; data: PatchedComunicacaoRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communicationsPartialUpdate>>,
  TError,
  { id: number; data: PatchedComunicacaoRequest },
  TContext
> => {
  const mutationKey = ["communicationsPartialUpdate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communicationsPartialUpdate>>,
    { id: number; data: PatchedComunicacaoRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return communicationsPartialUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunicationsPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof communicationsPartialUpdate>>
>;
export type CommunicationsPartialUpdateMutationBody = PatchedComunicacaoRequest;
export type CommunicationsPartialUpdateMutationError = ErrorType<unknown>;

export const useCommunicationsPartialUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof communicationsPartialUpdate>>,
      TError,
      { id: number; data: PatchedComunicacaoRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof communicationsPartialUpdate>>,
  TError,
  { id: number; data: PatchedComunicacaoRequest },
  TContext
> => {
  const mutationOptions =
    getCommunicationsPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * ViewSet para gerenciamento de comunicações formais.

Permite criar, listar, atualizar e excluir comunicações formais em projetos.
Comunicações formais são documentos oficiais como atas, memorandos e relatórios.

Endpoints:
- GET /comunicacoes/ - Lista todas as comunicações (com filtros)
- POST /comunicacoes/ - Cria uma nova comunicação
- GET /comunicacoes/{id}/ - Obtém detalhes de uma comunicação
- PUT/PATCH /comunicacoes/{id}/ - Atualiza uma comunicação
- DELETE /comunicacoes/{id}/ - Remove uma comunicação
 */
export const communicationsDestroy = (id: MaybeRef<number>) => {
  id = unref(id);

  return customMutator<void>({
    url: `/api/communications/${id}/`,
    method: "DELETE",
  });
};

export const getCommunicationsDestroyMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof communicationsDestroy>>,
    TError,
    { id: number },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof communicationsDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["communicationsDestroy"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof communicationsDestroy>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return communicationsDestroy(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type CommunicationsDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof communicationsDestroy>>
>;

export type CommunicationsDestroyMutationError = ErrorType<unknown>;

export const useCommunicationsDestroy = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof communicationsDestroy>>,
      TError,
      { id: number },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof communicationsDestroy>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getCommunicationsDestroyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
