# Generated by Django 5.2.1 on 2026-06-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_tenantinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='schema_name',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
