# Generated by Django 5.2.1 on 2026-06-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_client_schema_name_delete_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Feature flags por empresa (chave -> booleano).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parâmetros de configuração por empresa (chave -> valor).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='customers.client')),
            ],
            options={
                'verbose_name': 'Configuração do tenant',
                'verbose_name_plural': 'Configurações dos tenants',
            },
        ),
    ]
