/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `PROJETO` - Projeto
* `TAREFA` - Tarefa
 */
export type AlertaTipoEnum = typeof AlertaTipoEnum[keyof typeof AlertaTipoEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlertaTipoEnum = {
  PROJETO: 'PROJETO',
  TAREFA: 'TAREFA',
} as const;
