/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export interface AtribuicaoTarefa {
  readonly id: number;
  tarefa: number;
  usuario: number;
  readonly usuario_nome: string;
  readonly atribuido_em: string;
  /** @nullable */
  atribuido_por?: number | null;
  readonly atribuido_por_nome: string;
}
