/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { MembroProjeto } from './membroProjeto';

export interface PaginatedMembroProjetoList {
  count?: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results?: MembroProjeto[];
}
