/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { ProbabilidadeEnum } from './probabilidadeEnum';
import type { ImpactoEnum } from './impactoEnum';
import type { NovoStatus346Enum } from './novoStatus346Enum';

export interface PatchedRiscoRequest {
  projeto?: number;
  /** @minLength 1 */
  descricao?: string;
  probabilidade?: ProbabilidadeEnum;
  impacto?: ImpactoEnum;
  status?: NovoStatus346Enum;
  /** @nullable */
  responsavel_mitigacao?: number | null;
  /** @nullable */
  plano_mitigacao?: string | null;
  /** @nullable */
  plano_contingencia?: string | null;
  /** @nullable */
  criado_por?: number | null;
}
