# Generated by Django 4.2.10 on 2025-04-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("REQUISITO", "Requisito"),
                            ("DESIGN", "Design"),
                            ("MANUAL", "Manual"),
                            ("RELATORIO", "Relatório"),
                            ("ATA", "Ata de Reunião"),
                            ("OUTRO", "Outro"),
                        ],
                        default="OUTRO",
                        max_length=20,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(help_text="Tamanho em bytes"),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(help_text="Tipo MIME do arquivo", max_length=50),
                ),
                ("versao", models.CharField(default="1.0", max_length=20)),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="projects.projeto",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="tasks.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_upload"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("versao_anterior", models.CharField(max_length=20)),
                (
                    "arquivo_anterior",
                    models.FileField(upload_to="documentos/historico/"),
                ),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(help_text="Tamanho em bytes"),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="documents.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Documento",
                "verbose_name_plural": "Históricos de Documentos",
                "ordering": ["-data_alteracao"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="documents.documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["-criado_em"],
            },
        ),
    ]
