# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('documents', '0001_initial'),
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
        ('tasks', '0002_tarefa_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicodocumento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['tenant', '-criado_em'], name='documents_c_tenant__ce4835_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', '-data_upload'], name='documents_d_tenant__c1f5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='historicodocumento',
            index=models.Index(fields=['tenant', '-data_alteracao'], name='documents_h_tenant__ca72fc_idx'),
        ),
    ]
