/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import { TipoC51Enum } from ".././schemas";
import type {
  Comentario,
  Documento,
  HistoricoDocumento,
  PaginatedComentarioList,
  PaginatedDocumentoListList,
  PaginatedHistoricoDocumentoList,
} from ".././schemas";

export const getDocumentsListResponseMock = (
  overrideResponse: Partial<PaginatedDocumentoListList> = {},
): PaginatedDocumentoListList => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  next: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  previous: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: undefined, max: undefined }),
      projeto: faker.number.int({ min: undefined, max: undefined }),
      projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
      tarefa: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          null,
        ]),
        undefined,
      ]),
      tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
      titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
      tipo: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(TipoC51Enum)),
        undefined,
      ]),
      tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
      versao: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
      data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
      tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
      tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 50 } }),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDocumentsCreateResponseMock = (
  overrideResponse: Partial<Documento> = {},
): Documento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  projeto: faker.number.int({ min: undefined, max: undefined }),
  projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tarefa: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
  descricao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  tipo: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TipoC51Enum)),
    undefined,
  ]),
  tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: undefined, max: undefined }),
  tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  versao: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  enviado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
  atualizado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  comentarios: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    autor: faker.number.int({ min: undefined, max: undefined }),
    autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  historico: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
    arquivo_anterior: faker.internet.url(),
    tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
    alterado_por: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
    observacao: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getDocumentsRetrieveResponseMock = (
  overrideResponse: Partial<Documento> = {},
): Documento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  projeto: faker.number.int({ min: undefined, max: undefined }),
  projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tarefa: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
  descricao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  tipo: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TipoC51Enum)),
    undefined,
  ]),
  tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: undefined, max: undefined }),
  tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  versao: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  enviado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
  atualizado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  comentarios: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    autor: faker.number.int({ min: undefined, max: undefined }),
    autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  historico: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
    arquivo_anterior: faker.internet.url(),
    tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
    alterado_por: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
    observacao: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getDocumentsUpdateResponseMock = (
  overrideResponse: Partial<Documento> = {},
): Documento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  projeto: faker.number.int({ min: undefined, max: undefined }),
  projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tarefa: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
  descricao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  tipo: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TipoC51Enum)),
    undefined,
  ]),
  tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: undefined, max: undefined }),
  tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  versao: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  enviado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
  atualizado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  comentarios: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    autor: faker.number.int({ min: undefined, max: undefined }),
    autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  historico: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
    arquivo_anterior: faker.internet.url(),
    tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
    alterado_por: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
    observacao: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getDocumentsPartialUpdateResponseMock = (
  overrideResponse: Partial<Documento> = {},
): Documento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  projeto: faker.number.int({ min: undefined, max: undefined }),
  projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tarefa: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
  descricao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  tipo: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TipoC51Enum)),
    undefined,
  ]),
  tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: undefined, max: undefined }),
  tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  versao: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  enviado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
  atualizado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  comentarios: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    autor: faker.number.int({ min: undefined, max: undefined }),
    autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  historico: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
    arquivo_anterior: faker.internet.url(),
    tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
    alterado_por: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
    observacao: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getDocumentsAdicionarComentarioCreateResponseMock = (
  overrideResponse: Partial<Comentario> = {},
): Comentario => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  autor: faker.number.int({ min: undefined, max: undefined }),
  autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getDocumentsAssociarTarefaCreateResponseMock = (
  overrideResponse: Partial<Documento> = {},
): Documento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  projeto: faker.number.int({ min: undefined, max: undefined }),
  projeto_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tarefa: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  tarefa_titulo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  titulo: faker.string.alpha({ length: { min: 10, max: 200 } }),
  descricao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  tipo: faker.helpers.arrayElement([
    faker.helpers.arrayElement(Object.values(TipoC51Enum)),
    undefined,
  ]),
  tipo_display: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: undefined, max: undefined }),
  tipo_arquivo: faker.string.alpha({ length: { min: 10, max: 20 } }),
  versao: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  enviado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  enviado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_upload: `${faker.date.past().toISOString().split(".")[0]}Z`,
  atualizado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  comentarios: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    autor: faker.number.int({ min: undefined, max: undefined }),
    autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
    criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  })),
  historico: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int({ min: undefined, max: undefined }),
    documento: faker.number.int({ min: undefined, max: undefined }),
    versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
    arquivo_anterior: faker.internet.url(),
    tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
    alterado_por: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        null,
      ]),
      undefined,
    ]),
    alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
    data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
    observacao: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        null,
      ]),
      undefined,
    ]),
  })),
  ...overrideResponse,
});

export const getDocumentsDocumentHistoryRetrieveResponseMock = (
  overrideResponse: Partial<PaginatedHistoricoDocumentoList> = {},
): PaginatedHistoricoDocumentoList => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  next: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  previous: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: undefined, max: undefined }),
      documento: faker.number.int({ min: undefined, max: undefined }),
      versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
      arquivo_anterior: faker.internet.url(),
      tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
      alterado_por: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          null,
        ]),
        undefined,
      ]),
      alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
      data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
      observacao: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDocumentsComentariosListResponseMock = (
  overrideResponse: Partial<PaginatedComentarioList> = {},
): PaginatedComentarioList => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  next: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  previous: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: undefined, max: undefined }),
      documento: faker.number.int({ min: undefined, max: undefined }),
      autor: faker.number.int({ min: undefined, max: undefined }),
      autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
      texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
      criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDocumentsComentariosCreateResponseMock = (
  overrideResponse: Partial<Comentario> = {},
): Comentario => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  autor: faker.number.int({ min: undefined, max: undefined }),
  autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getDocumentsComentariosRetrieveResponseMock = (
  overrideResponse: Partial<Comentario> = {},
): Comentario => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  autor: faker.number.int({ min: undefined, max: undefined }),
  autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getDocumentsComentariosUpdateResponseMock = (
  overrideResponse: Partial<Comentario> = {},
): Comentario => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  autor: faker.number.int({ min: undefined, max: undefined }),
  autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getDocumentsComentariosPartialUpdateResponseMock = (
  overrideResponse: Partial<Comentario> = {},
): Comentario => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  autor: faker.number.int({ min: undefined, max: undefined }),
  autor_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  texto: faker.string.alpha({ length: { min: 10, max: 20 } }),
  criado_em: `${faker.date.past().toISOString().split(".")[0]}Z`,
  ...overrideResponse,
});

export const getDocumentsHistoricoListResponseMock = (
  overrideResponse: Partial<PaginatedHistoricoDocumentoList> = {},
): PaginatedHistoricoDocumentoList => ({
  count: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  next: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  previous: faker.helpers.arrayElement([
    faker.helpers.arrayElement([faker.internet.url(), null]),
    undefined,
  ]),
  results: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      id: faker.number.int({ min: undefined, max: undefined }),
      documento: faker.number.int({ min: undefined, max: undefined }),
      versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
      arquivo_anterior: faker.internet.url(),
      tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
      alterado_por: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.number.int({ min: undefined, max: undefined }),
          null,
        ]),
        undefined,
      ]),
      alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
      data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
      observacao: faker.helpers.arrayElement([
        faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        undefined,
      ]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDocumentsHistoricoRetrieveResponseMock = (
  overrideResponse: Partial<HistoricoDocumento> = {},
): HistoricoDocumento => ({
  id: faker.number.int({ min: undefined, max: undefined }),
  documento: faker.number.int({ min: undefined, max: undefined }),
  versao_anterior: faker.string.alpha({ length: { min: 10, max: 20 } }),
  arquivo_anterior: faker.internet.url(),
  tamanho_arquivo: faker.number.int({ min: 0, max: 9223372036854776000 }),
  alterado_por: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.number.int({ min: undefined, max: undefined }),
      null,
    ]),
    undefined,
  ]),
  alterado_por_nome: faker.string.alpha({ length: { min: 10, max: 20 } }),
  data_alteracao: `${faker.date.past().toISOString().split(".")[0]}Z`,
  observacao: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getDocumentsListMockHandler = (
  overrideResponse?:
    | PaginatedDocumentoListList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedDocumentoListList> | PaginatedDocumentoListList),
) => {
  return http.get("*/api/documents/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsListResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsCreateMockHandler = (
  overrideResponse?:
    | Documento
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Documento> | Documento),
) => {
  return http.post("*/api/documents/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsCreateResponseMock(),
      ),
      { status: 201, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsRetrieveMockHandler = (
  overrideResponse?:
    | Documento
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Documento> | Documento),
) => {
  return http.get("*/api/documents/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsRetrieveResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsUpdateMockHandler = (
  overrideResponse?:
    | Documento
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<Documento> | Documento),
) => {
  return http.put("*/api/documents/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsPartialUpdateMockHandler = (
  overrideResponse?:
    | Documento
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<Documento> | Documento),
) => {
  return http.patch("*/api/documents/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsPartialUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsDestroyMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.delete("*/api/documents/:id/", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};

export const getDocumentsAdicionarComentarioCreateMockHandler = (
  overrideResponse?:
    | Comentario
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Comentario> | Comentario),
) => {
  return http.post(
    "*/api/documents/:id/adicionar_comentario/",
    async (info) => {
      await delay(1000);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getDocumentsAdicionarComentarioCreateResponseMock(),
        ),
        { status: 201, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};

export const getDocumentsAssociarTarefaCreateMockHandler = (
  overrideResponse?:
    | Documento
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Documento> | Documento),
) => {
  return http.post("*/api/documents/:id/associar_tarefa/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsAssociarTarefaCreateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsDocumentHistoryRetrieveMockHandler = (
  overrideResponse?:
    | PaginatedHistoricoDocumentoList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<PaginatedHistoricoDocumentoList>
        | PaginatedHistoricoDocumentoList),
) => {
  return http.get("*/api/documents/:id/document_history/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsDocumentHistoryRetrieveResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosListMockHandler = (
  overrideResponse?:
    | PaginatedComentarioList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PaginatedComentarioList> | PaginatedComentarioList),
) => {
  return http.get("*/api/documents/comentarios/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsComentariosListResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosCreateMockHandler = (
  overrideResponse?:
    | Comentario
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Comentario> | Comentario),
) => {
  return http.post("*/api/documents/comentarios/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsComentariosCreateResponseMock(),
      ),
      { status: 201, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosRetrieveMockHandler = (
  overrideResponse?:
    | Comentario
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Comentario> | Comentario),
) => {
  return http.get("*/api/documents/comentarios/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsComentariosRetrieveResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosUpdateMockHandler = (
  overrideResponse?:
    | Comentario
    | ((
        info: Parameters<Parameters<typeof http.put>[1]>[0],
      ) => Promise<Comentario> | Comentario),
) => {
  return http.put("*/api/documents/comentarios/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsComentariosUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosPartialUpdateMockHandler = (
  overrideResponse?:
    | Comentario
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<Comentario> | Comentario),
) => {
  return http.patch("*/api/documents/comentarios/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsComentariosPartialUpdateResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsComentariosDestroyMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
) => {
  return http.delete("*/api/documents/comentarios/:id/", async (info) => {
    await delay(1000);
    if (typeof overrideResponse === "function") {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 204 });
  });
};

export const getDocumentsHistoricoListMockHandler = (
  overrideResponse?:
    | PaginatedHistoricoDocumentoList
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<PaginatedHistoricoDocumentoList>
        | PaginatedHistoricoDocumentoList),
) => {
  return http.get("*/api/documents/historico/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsHistoricoListResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getDocumentsHistoricoRetrieveMockHandler = (
  overrideResponse?:
    | HistoricoDocumento
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<HistoricoDocumento> | HistoricoDocumento),
) => {
  return http.get("*/api/documents/historico/:id/", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDocumentsHistoricoRetrieveResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};
export const getDocumentosMock = () => [
  getDocumentsListMockHandler(),
  getDocumentsCreateMockHandler(),
  getDocumentsRetrieveMockHandler(),
  getDocumentsUpdateMockHandler(),
  getDocumentsPartialUpdateMockHandler(),
  getDocumentsDestroyMockHandler(),
  getDocumentsAdicionarComentarioCreateMockHandler(),
  getDocumentsAssociarTarefaCreateMockHandler(),
  getDocumentsDocumentHistoryRetrieveMockHandler(),
  getDocumentsComentariosListMockHandler(),
  getDocumentsComentariosCreateMockHandler(),
  getDocumentsComentariosRetrieveMockHandler(),
  getDocumentsComentariosUpdateMockHandler(),
  getDocumentsComentariosPartialUpdateMockHandler(),
  getDocumentsComentariosDestroyMockHandler(),
  getDocumentsHistoricoListMockHandler(),
  getDocumentsHistoricoRetrieveMockHandler(),
];
