/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer para o modelo Categoria.

Utilizado para serializar/desserializar dados da categoria.
Inclui todos os campos do modelo.
 */
export interface CategoriaRequest {
  /**
   * @minLength 1
   * @maxLength 100
   */
  nome: string;
  /** @nullable */
  descricao?: string | null;
}
