/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { TipoC51Enum } from "./tipoC51Enum";

export interface DocumentoRequest {
  projeto: number;
  /** @nullable */
  tarefa?: number | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  titulo: string;
  /** @nullable */
  descricao?: string | null;
  tipo?: TipoC51Enum;
  arquivo: Blob;
  /**
   * @minLength 1
   * @maxLength 20
   */
  versao?: string;
  /** @nullable */
  enviado_por?: number | null;
}
