/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer simplificado para listagem de equipes
 */
export interface EquipeList {
  readonly id: number;
  /** @maxLength 100 */
  nome: string;
  /** Nome completo do criador da equipe. */
  readonly criado_por_nome: string;
  readonly criado_em: string;
  /** Número total de membros nesta equipe. */
  readonly total_membros: number;
}
