/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { NovoStatusBbcEnum } from './novoStatusBbcEnum';

export interface HistoricoStatusTarefa {
  readonly id: number;
  tarefa: number;
  status_anterior: NovoStatusBbcEnum;
  readonly status_anterior_display: string;
  novo_status: NovoStatusBbcEnum;
  readonly novo_status_display: string;
  /** @nullable */
  alterado_por?: number | null;
  readonly alterado_por_nome: string;
  readonly alterado_em: string;
}
