/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export interface HistoricoDocumento {
  readonly id: number;
  documento: number;
  /** @maxLength 20 */
  versao_anterior: string;
  arquivo_anterior: string;
  /**
   * Tamanho em bytes
   * @minimum 0
   * @maximum 9223372036854776000
   */
  tamanho_arquivo: number;
  /** @nullable */
  alterado_por?: number | null;
  readonly alterado_por_nome: string;
  readonly data_alteracao: string;
  /** @nullable */
  observacao?: string | null;
}
