/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `BAIXO` - Baixo
 * `MEDIO` - Médio
 * `ALTO` - Alto
 */
export type ImpactoEnum = (typeof ImpactoEnum)[keyof typeof ImpactoEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImpactoEnum = {
  BAIXO: "BAIXO",
  MEDIO: "MEDIO",
  ALTO: "ALTO",
} as const;
