/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { MembroProjetoPapelEnum } from "./membroProjetoPapelEnum";

/**
 * Serializer para membros de projeto.

Inclui informações básicas do usuário e seu papel no projeto.
 */
export interface MembroProjetoRequest {
  usuario: number;
  papel: MembroProjetoPapelEnum;
  projeto: number;
}
