/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { MembroProjetoPapelEnum } from "./membroProjetoPapelEnum";

/**
 * Serializer para membros de projeto.

Inclui informações básicas do usuário e seu papel no projeto.
 */
export interface MembroProjeto {
  readonly id: number;
  readonly usuario_id: number;
  readonly username: string;
  readonly full_name: string;
  papel: MembroProjetoPapelEnum;
  /** Nome do papel para exibição */
  readonly papel_display: string;
  projeto: number;
}
