/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `A_FAZER` - A Fazer
* `EM_ANDAMENTO` - Em Andamento
* `FEITO` - Feito
 */
export type NovoStatusBbcEnum = typeof NovoStatusBbcEnum[keyof typeof NovoStatusBbcEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NovoStatusBbcEnum = {
  A_FAZER: 'A_FAZER',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  FEITO: 'FEITO',
} as const;
