/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer para o modelo OrcamentoTarefa.

Inclui campos para o orçamento de uma tarefa específica e informações de aprovação.
Adiciona campos de leitura para nomes relacionados (aprovador, tarefa, projeto da tarefa)
e campos calculados (valor utilizado, valor restante, percentual utilizado).
 */
export interface OrcamentoTarefa {
  readonly id: number;
  tarefa: number;
  readonly tarefa_titulo: string;
  readonly projeto_nome: string;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  valor: string;
  readonly data_aprovacao: string;
  /** @nullable */
  aprovado_por?: number | null;
  readonly aprovado_por_nome: string;
  /** @nullable */
  observacoes?: string | null;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  readonly valor_utilizado: string;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  readonly valor_restante: string;
  /** @pattern ^-?\d{0,3}(?:\.\d{0,2})?$ */
  readonly percentual_utilizado: string;
}
