/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `EMAIL` - E-mail
 * `SISTEMA` - Sistema
 * `AMBOS` - Ambos
 * `NENHUM` - Nenhum
 */
export type ProjetoStatusEnum =
  (typeof ProjetoStatusEnum)[keyof typeof ProjetoStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjetoStatusEnum = {
  EMAIL: "EMAIL",
  SISTEMA: "SISTEMA",
  AMBOS: "AMBOS",
  NENHUM: "NENHUM",
} as const;
