/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export type RisksRiscosListStatus =
  (typeof RisksRiscosListStatus)[keyof typeof RisksRiscosListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RisksRiscosListStatus = {
  ACEITO: "ACEITO",
  ELIMINADO: "ELIMINADO",
  EM_ANALISE: "EM_ANALISE",
  IDENTIFICADO: "IDENTIFICADO",
  MITIGADO: "MITIGADO",
} as const;
