/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { NovoStatusBbcEnum } from "./novoStatusBbcEnum";

/**
 * Serializer para atualizar o status de uma tarefa.
 */
export interface TasksUpdateStatusRequest {
  status: NovoStatusBbcEnum;
  /** Comentário opcional sobre a mudança de status. */
  comentario?: string;
}
