/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { TasksTarefasAssociarSprintCreateBodySprintId } from './tasksTarefasAssociarSprintCreateBodySprintId';

export type TasksTarefasAssociarSprintCreateBody = {
  /** ID da sprint a ser associada. Use 0 ou null para remover a associação. */
  sprint_id: TasksTarefasAssociarSprintCreateBodySprintId;
};
