/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export type TasksTarefasListParams = {
  /**
   * Filtra tarefas atrasadas (data_termino < hoje e status não é 'FEITO').
   */
  atrasada?: boolean;
  data_inicio_range_after?: string;
  data_inicio_range_before?: string;
  data_termino_range_after?: string;
  data_termino_range_before?: string;
  /**
   * Filtra por parte da descrição (case-insensitive).
   */
  descricao?: string;
  /**
   * Filtra apenas as tarefas atribuídas ao usuário autenticado.
   */
  minhas_tarefas?: boolean;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Filtra por prioridade (pode ser uma ou múltiplas, separadas por vírgula).
   */
  prioridade?: string;
  projeto?: number;
  /**
   * Filtra tarefas por um ID de usuário responsável específico.
   */
  responsavel_id?: string;
  /**
   * A search term.
   */
  search?: string;
  /**
   * Filtra tarefas sem responsáveis atribuídos.
   */
  sem_responsavel?: boolean;
  /**
   * Filtra tarefas que não estão associadas a nenhuma sprint.
   */
  sem_sprint?: boolean;
  sprint?: number;
  /**
   * Filtra por status (pode ser um ou múltiplos, separados por vírgula).
   */
  status?: string;
  /**
   * Filtra por parte do título (case-insensitive).
   */
  titulo?: string;
};
