/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export type TeamsEquipesListParams = {
/**
 * Filtrar apenas minhas equipes
 */
minhas_equipes?: boolean;
/**
 * Which field to use when ordering the results.
 */
ordering?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * A search term.
 */
search?: string;
/**
 * Filtrar por nome ou descrição
 */
texto?: string;
/**
 * Filtrar por membro da equipe
 */
usuario?: number;
};
