/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */

export interface TokenObtainPairRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}
