/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { RoleEnum } from './roleEnum';

/**
 * Serializer específico para o registro de novos usuários.
Pede apenas os campos essenciais e valida a senha.
 */
export interface UserCreateRequest {
  /**
   * @minLength 1
   * @maxLength 30
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  full_name: string;
  /** @minLength 1 */
  password: string;
  role?: RoleEnum;
}
