/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Planify API
 * Sistema de Gerenciamento de Projetos
 * OpenAPI spec version: 1.0.0
 */
import type { ThemePreferenceEnum } from './themePreferenceEnum';

export interface UserProfile {
  user: number;
  /**
   * @maxLength 20
   * @nullable
   */
  phone?: string | null;
  /** @nullable */
  profile_picture?: string | null;
  theme_preference?: ThemePreferenceEnum;
  email_notifications?: boolean;
  system_notifications?: boolean;
}
