# Generated by Django 4.2.10 on 2025-04-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe",
                "verbose_name_plural": "Equipes",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="PermissaoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("PO", "Product Owner"),
                            ("SM", "Scrum Master"),
                            ("DEV", "Desenvolvedor"),
                            ("QA", "Analista de Qualidade"),
                            ("DESIGN", "Designer"),
                            ("ANALISTA", "Analista"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("TAREFAS", "Tarefas"),
                            ("SPRINTS", "Sprints"),
                            ("DOCUMENTOS", "Documentos"),
                            ("RISCOS", "Riscos"),
                            ("CUSTOS", "Custos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permissao",
                    models.CharField(
                        choices=[
                            ("VISUALIZAR", "Visualizar"),
                            ("CRIAR", "Criar"),
                            ("EDITAR", "Editar"),
                            ("EXCLUIR", "Excluir"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissoes",
                        to="teams.equipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão de Equipe",
                "verbose_name_plural": "Permissões de Equipe",
                "unique_together": {("papel", "equipe", "modulo", "permissao")},
            },
        ),
        migrations.CreateModel(
            name="MembroEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("PO", "Product Owner"),
                            ("SM", "Scrum Master"),
                            ("DEV", "Desenvolvedor"),
                            ("QA", "Analista de Qualidade"),
                            ("DESIGN", "Designer"),
                            ("ANALISTA", "Analista"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adicionado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "adicionado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membros_adicionados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="teams.equipe",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Equipe",
                "verbose_name_plural": "Membros da Equipe",
                "unique_together": {("equipe", "usuario")},
            },
        ),
    ]
