# Generated by Django 4.2.7 on 2025-05-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('ASSIGN', 'Assign'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('COMMENT', 'Comment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('PROJECTS', 'Projects'), ('TASKS', 'Tasks'), ('TEAMS', 'Teams'), ('RESOURCES', 'Resources'), ('COMMUNICATIONS', 'Communications'), ('RISKS', 'Risks'), ('COSTS', 'Costs'), ('DOCUMENTS', 'Documents'), ('REPORTS', 'Reports'), ('USERS', 'Users'), ('SETTINGS', 'Settings'), ('DASHBOARD', 'Dashboard'), ('NOTIFICATIONS', 'Notifications'), ('APPROVALS', 'Approvals')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEADER', 'Team Leader'), ('TEAM_MEMBER', 'Team Member'), ('STAKEHOLDER', 'Stakeholder/Client'), ('AUDITOR', 'Auditor')], default='TEAM_MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField()),
                ('success', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Attempt',
                'verbose_name_plural': 'Access Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
