# Generated by Django 5.2.1 on 2025-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_last_login_attempt_alter_permission_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlacklistedTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
            ],
        ),
    ]
