# Generated by Django 5.2.1 on 2025-06-21 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_blacklistedtokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedtokens",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Token Blacklisted",
                "verbose_name_plural": "Tokens Blacklisted",
            },
        ),
        migrations.AddField(
            model_name="blacklistedtokens",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blacklistedtokens",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
