# Generated by Django 5.2.1 on 2025-06-24 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_add_security_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Alteração de Senha'), ('PASSWORD_RESET_REQUEST', 'Solicitação de Reset de Senha'), ('PROFILE_UPDATE', 'Atualização de Perfil'), ('PERMISSION_CHANGE', 'Alteração de Permissão'), ('ACCOUNT_LOCKED', 'Conta Bloqueada'), ('ACCOUNT_UNLOCKED', 'Conta Desbloqueada'), ('FAILED_LOGIN', 'Tentativa de Login Falhada'), ('USER_CREATED', 'Usuário Criado'), ('USER_ACTIVATED', 'Usuário Ativado'), ('USER_DEACTIVATED', 'Usuário Desativado')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='users_audit_user_id_c6aa5b_idx'), models.Index(fields=['timestamp'], name='users_audit_timesta_45d1d4_idx'), models.Index(fields=['ip_address'], name='users_audit_ip_addr_b1d183_idx')],
            },
        ),
    ]
