# Generated by Django 5.2.1 on 2025-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
    ]
