# Generated by Django 5.2.1 on 2025-06-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_password_change_required"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlacklistedTokens",
        ),
    ]
