# Generated by Django 4.2.10 on 2025-04-23 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="OrcamentoTarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_aprovacao", models.DateField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orcamentos_tarefa_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarefa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamento",
                        to="tasks.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento de Tarefa",
                "verbose_name_plural": "Orçamentos de Tarefas",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("data_aprovacao", models.DateField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "aprovado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orcamentos_aprovados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orcamento",
                        to="projects.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento de Projeto",
                "verbose_name_plural": "Orçamentos de Projetos",
            },
        ),
        migrations.CreateModel(
            name="Custo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FIXO", "Custo Fixo"),
                            ("VARIAVEL", "Custo Variável"),
                            ("RECORRENTE", "Custo Recorrente"),
                        ],
                        default="FIXO",
                        max_length=20,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "comprovante",
                    models.FileField(blank=True, null=True, upload_to="comprovantes/"),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custos",
                        to="costs.categoria",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos",
                        to="projects.projeto",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custos",
                        to="tasks.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custo",
                "verbose_name_plural": "Custos",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PROJETO", "Projeto"), ("TAREFA", "Tarefa")],
                        max_length=10,
                    ),
                ),
                ("percentual", models.DecimalField(decimal_places=2, max_digits=5)),
                ("mensagem", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("RESOLVIDO", "Resolvido"),
                            ("IGNORADO", "Ignorado"),
                        ],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_resolucao", models.DateTimeField(blank=True, null=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="projects.projeto",
                    ),
                ),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_resolvidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="tasks.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Orçamento",
                "verbose_name_plural": "Alertas de Orçamento",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
