# Generated by Django 4.2.7 on 2025-06-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tarefa_atualizado_por'),
        ('projects', '0001_initial'),
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_do_projeto', to='projects.projeto'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_da_tarefa', to='tasks.tarefa'),
        ),
    ]
