# Generated by Django 5.2.1 on 2026-06-03 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_custo_projeto_alter_custo_tarefa'),
        ('customers', '0004_remove_client_schema_name_delete_domain'),
        ('projects', '0002_alter_membroprojeto_unique_together_and_more'),
        ('tasks', '0002_tarefa_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoprojeto',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentotarefa',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tenant', '-data_criacao'], name='costs_alert_tenant__21179c_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['tenant', 'nome'], name='costs_categ_tenant__87be5e_idx'),
        ),
        migrations.AddIndex(
            model_name='custo',
            index=models.Index(fields=['tenant', '-data'], name='costs_custo_tenant__fd7df3_idx'),
        ),
    ]
