name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Executa todo domingo à meia-noite

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        
    - name: Run Bandit (Python Security Scanner)
      run: |
        bandit -r backend/ -x backend/tests/,backend/*/tests/
        
    - name: Check Python dependencies for vulnerabilities
      run: |
        safety check -r backend/requirements.txt
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Node.js security tools
      run: |
        npm install -g npm-audit-resolver
        
    - name: Check JavaScript dependencies for vulnerabilities
      run: |
        cd frontend
        npm audit --production
